# Generated by Django 5.0.14 on 2025-08-02 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('view_only', 'View Only'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('manage', 'Manage'), ('admin', 'Admin'), ('approve', 'Approve'), ('reject', 'Reject'), ('custom', 'Custom')], default='view_only', max_length=50)),
                ('module', models.CharField(choices=[('auction_management', 'Auction Management'), ('bid_management', 'Bid Management'), ('product_management', 'Product Management'), ('user_management', 'User Management'), ('seller_management', 'Seller Management'), ('buyer_management', 'Buyer Management'), ('payment_processing', 'Payment Processing'), ('document_verification', 'Document Verification'), ('notifications', 'Notifications'), ('reporting', 'Reporting'), ('analytics', 'Analytics'), ('system_configuration', 'System Configuration'), ('compliance', 'Compliance'), ('support', 'Support'), ('messaging', 'Messaging'), ('logistics', 'Logistics'), ('inventory', 'Inventory'), ('financial_reports', 'Financial Reports'), ('dispute_resolution', 'Dispute Resolution'), ('platform_settings', 'Platform Settings')], default='auction_management', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bidr_permissions',
                'ordering': ['module', 'name'],
                'indexes': [models.Index(fields=['module', 'type'], name='bidr_permis_module_8779c9_idx'), models.Index(fields=['is_active'], name='bidr_permis_is_acti_35f8ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.permission')),
            ],
            options={
                'db_table': 'bidr_role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserRoleType',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('company_type', models.CharField(choices=[('individual_seller', 'Individual Seller'), ('business_seller', 'Business Seller'), ('corporate_seller', 'Corporate Seller'), ('individual_buyer', 'Individual Buyer'), ('business_buyer', 'Business Buyer'), ('corporate_buyer', 'Corporate Buyer'), ('auction_house', 'Auction House'), ('platform_admin', 'Platform Admin'), ('super_admin', 'Super Admin'), ('moderator', 'Moderator'), ('support_agent', 'Support Agent'), ('financial_officer', 'Financial Officer'), ('compliance_officer', 'Compliance Officer')], max_length=50)),
                ('role_level', models.CharField(choices=[('super_admin', 'Super Admin'), ('platform_admin', 'Platform Admin'), ('senior_management', 'Senior Management'), ('middle_management', 'Middle Management'), ('operational', 'Operational'), ('specialist', 'Specialist'), ('basic_user', 'Basic User'), ('guest', 'Guest'), ('temporary', 'Temporary')], max_length=50)),
                ('role_job_function', models.CharField(choices=[('super_admin', 'Super Administrator'), ('platform_admin', 'Platform Administrator'), ('auction_manager', 'Auction Manager'), ('seller_manager', 'Seller Manager'), ('buyer_manager', 'Buyer Manager'), ('payment_processor', 'Payment Processor'), ('document_verifier', 'Document Verifier'), ('compliance_manager', 'Compliance Manager'), ('support_manager', 'Support Manager'), ('financial_analyst', 'Financial Analyst'), ('marketing_manager', 'Marketing Manager'), ('system_analyst', 'System Analyst'), ('quality_assurance', 'Quality Assurance'), ('customer_service', 'Customer Service'), ('logistics_coordinator', 'Logistics Coordinator'), ('dispute_resolver', 'Dispute Resolver'), ('content_moderator', 'Content Moderator'), ('data_analyst', 'Data Analyst'), ('security_officer', 'Security Officer')], max_length=50)),
                ('function_department', models.CharField(choices=[('administration', 'Administration'), ('operations', 'Operations'), ('sales_marketing', 'Sales & Marketing'), ('customer_service', 'Customer Service'), ('finance_accounting', 'Finance & Accounting'), ('compliance_legal', 'Compliance & Legal'), ('technology', 'Technology'), ('quality_assurance', 'Quality Assurance'), ('logistics_fulfillment', 'Logistics & Fulfillment'), ('business_development', 'Business Development'), ('product_management', 'Product Management'), ('data_analytics', 'Data & Analytics'), ('security', 'Security'), ('human_resources', 'Human Resources'), ('vendor_management', 'Vendor Management')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(related_name='role_types', through='permissions.RolePermission', to='permissions.permission')),
            ],
            options={
                'db_table': 'bidr_user_role_types',
                'ordering': ['company_type', 'role_level', 'role_name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('assigned_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='permissions.userroletype')),
            ],
            options={
                'db_table': 'bidr_user_roles',
            },
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.userroletype'),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('user_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('permission_type', models.CharField(choices=[('grant', 'Grant'), ('deny', 'Deny')], default='grant', help_text='Grant adds permission, Deny removes it even if role has it', max_length=20)),
                ('assigned_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='permissions.permission')),
            ],
            options={
                'db_table': 'bidr_user_permissions',
                'indexes': [models.Index(fields=['user_email', 'is_active'], name='bidr_user_p_user_em_177206_idx'), models.Index(fields=['permission', 'is_active'], name='bidr_user_p_permiss_e51b45_idx')],
                'unique_together': {('user_email', 'permission')},
            },
        ),
        migrations.AddIndex(
            model_name='userroletype',
            index=models.Index(fields=['company_type', 'role_level'], name='bidr_user_r_company_2319b2_idx'),
        ),
        migrations.AddIndex(
            model_name='userroletype',
            index=models.Index(fields=['is_active'], name='bidr_user_r_is_acti_c3980d_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user_email', 'is_active'], name='bidr_user_r_user_em_22fca6_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='bidr_user_r_role_id_1436d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user_email', 'role')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_active'], name='bidr_role_p_role_id_c714c3_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission', 'is_active'], name='bidr_role_p_permiss_f8c906_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
