# Generated by Django 5.1.11 on 2025-08-30 17:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(help_text='UUID of the user from authentication service')),
                ('code', models.CharField(help_text='Unique referral code like BIDR12345678', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('total_uses', models.IntegerField(default=0)),
                ('max_uses', models.IntegerField(default=100, help_text='Maximum number of uses allowed')),
                ('referrer_reward_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Amount rewarded to referrer when someone signs up', max_digits=10)),
                ('referee_reward_amount', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Amount rewarded to new user who signs up', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_uuid'], name='rewards_ref_user_uu_5d1ec5_idx'), models.Index(fields=['code'], name='rewards_ref_code_98aa60_idx'), models.Index(fields=['status'], name='rewards_ref_status_fcad81_idx')],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referrer_uuid', models.UUIDField(help_text='UUID of the user who referred')),
                ('referee_uuid', models.UUIDField(help_text='UUID of the new user who was referred')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('referrer_rewarded', models.BooleanField(default=False)),
                ('referee_rewarded', models.BooleanField(default=False)),
                ('referrer_reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referee_reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='rewards.referralcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardsCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], default='DRAFT', max_length=20)),
                ('campaign_type', models.CharField(choices=[('REFERRAL_BONUS', 'Referral Bonus'), ('REVIEW_BONUS', 'Review Bonus'), ('FIRST_TIME_BONUS', 'First Time Bonus'), ('LOYALTY_BONUS', 'Loyalty Bonus')], max_length=30)),
                ('reward_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Points awarded for this campaign', max_digits=10)),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiply standard rewards by this amount', max_digits=5)),
                ('bonus_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional bonus points to award', max_digits=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('current_participants', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'starts_at', 'ends_at'], name='rewards_rew_status_1f2619_idx'), models.Index(fields=['campaign_type'], name='rewards_rew_campaig_c6c237_idx')],
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(help_text='UUID of the user receiving the reward')),
                ('transaction_type', models.CharField(choices=[('REFERRAL_REFERRER', 'Referral Reward (Referrer)'), ('REFERRAL_REFEREE', 'Referral Reward (Referee)'), ('REVIEW_BONUS', 'Review Writing Bonus'), ('RATING_BONUS', 'Rating Bonus'), ('LOYALTY_BONUS', 'Loyalty Bonus'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('REDEMPTION', 'Points Redemption')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('points_amount', models.DecimalField(decimal_places=2, help_text='Points awarded (can be negative for redemptions)', max_digits=10)),
                ('cash_equivalent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash value equivalent', max_digits=10)),
                ('reference_id', models.CharField(blank=True, help_text='External reference (e.g., review_id, product_id)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('referral', models.ForeignKey(blank=True, help_text='Related referral if this is a referral reward', null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.referral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRewardsSummary',
            fields=[
                ('user_uuid', models.UUIDField(help_text='UUID of the user', primary_key=True, serialize=False)),
                ('current_points_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_points_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_points_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_referrals_made', models.IntegerField(default=0)),
                ('successful_referrals', models.IntegerField(default=0)),
                ('total_referral_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_reviews_written', models.IntegerField(default=0)),
                ('total_ratings_given', models.IntegerField(default=0)),
                ('review_bonus_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tier_level', models.IntegerField(default=1, help_text='Tier level: 1=Basic, 2=Bronze, 3=Silver, 4=Gold, 5=Platinum', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-current_points_balance'],
                'indexes': [models.Index(fields=['current_points_balance'], name='rewards_use_current_506659_idx'), models.Index(fields=['tier_level'], name='rewards_use_tier_le_bdaca1_idx'), models.Index(fields=['is_active'], name='rewards_use_is_acti_99aec9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer_uuid'], name='rewards_ref_referre_4c9e14_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referee_uuid'], name='rewards_ref_referee_1f2920_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='rewards_ref_status_073727_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('referral_code', 'referee_uuid')},
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['user_uuid'], name='rewards_rew_user_uu_cb8135_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['transaction_type'], name='rewards_rew_transac_716544_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['status'], name='rewards_rew_status_d97116_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['created_at'], name='rewards_rew_created_b60c6d_idx'),
        ),
    ]
