apiVersion: v1
kind: Service
metadata:
  name: product-management-nodeport
  namespace: bidr
  labels:
    app: product-management-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30080  # Accessible via <NodeIP>:30080
    protocol: TCP
  selector:
    app: product-management-service
