# Generated by Django 5.0.14 on 2025-08-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notifications', '0002_notification_is_active_notificationbatch_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationbatch',
            old_name='notifications_service',
            new_name='notifications',
        ),
    ]
