# Generated by Django 5.0.14 on 2025-08-26 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_requests', '0001_initial'),
        ('quotes', '0002_alter_quote_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Order identifier', primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='Human-readable order number', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Payment Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=12)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Delivery charges', max_digits=10, null=True)),
                ('installation_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Installation charges', max_digits=10, null=True)),
                ('currency', models.CharField(default='ZAR', help_text='Currency code', max_length=3)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (e.g., Credit Card, EFT, etc.)', max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment gateway reference number', max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('delivery_address', models.JSONField(blank=True, help_text='Delivery address details', null=True)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, help_text='Expected delivery date', null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, help_text='Actual delivery date', null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Shipping tracking number', max_length=100, null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special delivery or handling instructions', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal order notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_id', models.ForeignKey(help_text='Buyer who created the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('quote_id', models.ForeignKey(help_text='Reference to the accepted quote', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='quotes.quote')),
                ('request_id', models.ForeignKey(help_text='Reference to the original product request', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product_requests.productrequest')),
                ('seller_id', models.ForeignKey(help_text='Seller fulfilling the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer_id', 'status'], name='orders_buyer_i_ca4401_idx'), models.Index(fields=['seller_id', 'status'], name='orders_seller__7a6b96_idx'), models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'), models.Index(fields=['payment_status'], name='orders_payment_050188_idx'), models.Index(fields=['order_number'], name='orders_order_n_1336be_idx')],
            },
        ),
    ]
