# Generated by Django 5.0.14 on 2025-09-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('product_requests', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quote_id',
            field=models.ForeignKey(help_text='Reference to the accepted quote', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='consumer_electronics',
            field=models.ForeignKey(blank=True, help_text='Detailed consumer electronics specifications if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='product_requests.consumerelectronics'),
        ),
        migrations.AddField(
            model_name='order',
            name='request_id',
            field=models.ForeignKey(help_text='Reference to the original product request', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product_requests.productrequest'),
        ),
        migrations.AddField(
            model_name='requestimage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_requests.productrequest'),
        ),
        migrations.AddField(
            model_name='requestmessage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='product_requests.productrequest'),
        ),
        migrations.AddField(
            model_name='requestspecification',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product_requests.productrequest'),
        ),
        migrations.AddField(
            model_name='requesttemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_templates', to='categories.category'),
        ),
        migrations.AddField(
            model_name='requestwatchlist',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='product_requests.productrequest'),
        ),
        migrations.AddIndex(
            model_name='vehiclespares',
            index=models.Index(fields=['vehicle_make', 'vehicle_model'], name='vehicle_spa_vehicle_c62cac_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclespares',
            index=models.Index(fields=['part_category'], name='vehicle_spa_part_ca_ec558a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclespares',
            index=models.Index(fields=['urgency'], name='vehicle_spa_urgency_72a2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclespares',
            index=models.Index(fields=['condition_preference'], name='vehicle_spa_conditi_7b954e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclespares',
            index=models.Index(fields=['created_at'], name='vehicle_spa_created_66a800_idx'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='vehicle_spares',
            field=models.ForeignKey(blank=True, help_text='Detailed vehicle spares specifications if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='product_requests.vehiclespares'),
        ),
        migrations.AddIndex(
            model_name='vehicletyresrims',
            index=models.Index(fields=['select_tyres_rims'], name='vehicle_tyr_select__226d65_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletyresrims',
            index=models.Index(fields=['vehicle_type'], name='vehicle_tyr_vehicle_a2d834_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletyresrims',
            index=models.Index(fields=['urgency'], name='vehicle_tyr_urgency_b91aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletyresrims',
            index=models.Index(fields=['created_at'], name='vehicle_tyr_created_5542bf_idx'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='vehicle_tyres_rims',
            field=models.ForeignKey(blank=True, help_text='Detailed tyres and rims specifications if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='product_requests.vehicletyresrims'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer_id', 'status'], name='orders_buyer_i_de73e4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller_id', 'status'], name='orders_seller__0c477d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_payment_050188_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='requestmessage',
            index=models.Index(fields=['request', 'created_at'], name='product_req_request_3606ae_idx'),
        ),
        migrations.AddIndex(
            model_name='requestmessage',
            index=models.Index(fields=['sender_id'], name='product_req_sender__742078_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestspecification',
            unique_together={('request', 'name')},
        ),
        migrations.AddIndex(
            model_name='requesttemplate',
            index=models.Index(fields=['category', 'is_active'], name='product_req_categor_4d724f_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttemplate',
            index=models.Index(fields=['request_type', 'is_active'], name='product_req_request_c78899_idx'),
        ),
        migrations.AddIndex(
            model_name='requestwatchlist',
            index=models.Index(fields=['user_id', 'created_at'], name='product_req_user_id_6898b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestwatchlist',
            unique_together={('request', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['status', 'category'], name='product_req_status_aa566b_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['buyer_id', 'status'], name='product_req_buyer_i_98c66e_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['category', 'status'], name='product_req_categor_d57c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['auth_user_uid'], name='product_req_auth_us_24038d_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['expiry_date'], name='product_req_expiry__bd7b48_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['urgency_timeline'], name='product_req_urgency_a3c9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['created_at'], name='product_req_created_19e00b_idx'),
        ),
    ]
