# Generated by Django 5.2.5 on 2025-08-27 20:00

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_requests', '0002_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='auth_user_uid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Authentication user UUID for filtering user-specific requests'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['auth_user_uid'], name='product_req_auth_us_24038d_idx'),
        ),
    ]
