# Generated by Django 5.1.11 on 2025-09-07 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Payment Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('PURCHASED', 'Purchased'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='CollectionCode',
            fields=[
                ('code_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Collection code identifier', primary_key=True, serialize=False)),
                ('pin_code', models.CharField(help_text='4-digit PIN code for collection', max_length=4)),
                ('buyer_id', models.UUIDField(help_text='UUID of the buyer from authentication service')),
                ('seller_id', models.UUIDField(help_text='UUID of the seller from authentication service')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the code has been used')),
                ('expires_at', models.DateTimeField(help_text='When the code expires (5 minutes from generation)')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the code was used', null=True)),
                ('confirmed_by_seller_id', models.UUIDField(blank=True, help_text='UUID of seller who confirmed the code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(help_text='Reference to the order', on_delete=django.db.models.deletion.CASCADE, related_name='collection_codes', to='product_requests.order')),
            ],
            options={
                'db_table': 'collection_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id', 'is_used'], name='collection__order_i_6774dc_idx'), models.Index(fields=['buyer_id'], name='collection__buyer_i_9f26a0_idx'), models.Index(fields=['seller_id'], name='collection__seller__18b19f_idx'), models.Index(fields=['expires_at'], name='collection__expires_a1beff_idx'), models.Index(fields=['pin_code'], name='collection__pin_cod_ffa2ba_idx')],
            },
        ),
    ]
