# Generated by Django 5.0.14 on 2025-08-10 00:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_conversations', '0001_initial'),
        ('chat_messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(help_text='SHA-256 hash', max_length=64, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_category', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('archive', 'Archive'), ('code', 'Code File'), ('other', 'Other')], max_length=20)),
                ('upload_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('scanning', 'Virus Scanning'), ('available', 'Available'), ('quarantined', 'Quarantined'), ('deleted', 'Deleted'), ('expired', 'Expired')], default='uploading', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('virus_scan_result', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('suspicious', 'Suspicious'), ('error', 'Scan Error')], default='pending', max_length=20)),
                ('scan_engine', models.CharField(blank=True, max_length=50)),
                ('scan_details', models.JSONField(blank=True, default=dict)),
                ('content_analysis', models.JSONField(blank=True, default=dict, help_text='AI/ML analysis results')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from file')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image/video width', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image/video height', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Audio/video duration in seconds', null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('access_token', models.CharField(blank=True, help_text='Token for accessing file', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='chat_conversations.conversation')),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='chat_messaging.message')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
            },
        ),
        migrations.CreateModel(
            name='FileThumbnail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_type', models.CharField(choices=[('small', '150x150'), ('medium', '300x300'), ('large', '600x600'), ('preview', '1200x800')], max_length=20)),
                ('thumbnail_path', models.ImageField(upload_to='thumbnails/%Y/%m/%d/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generation_method', models.CharField(blank=True, help_text='Tool/library used', max_length=50)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='file_handler.fileupload')),
            ],
            options={
                'verbose_name': 'File Thumbnail',
                'verbose_name_plural': 'File Thumbnails',
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('download', 'Download'), ('edit', 'Edit'), ('admin', 'Admin')], default='view', max_length=20)),
                ('share_token', models.CharField(max_length=64, unique=True)),
                ('public_share', models.BooleanField(default=False)),
                ('password_protected', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('requires_login', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_log', models.JSONField(blank=True, default=list)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='file_handler.fileupload')),
            ],
            options={
                'verbose_name': 'File Share',
                'verbose_name_plural': 'File Shares',
            },
        ),
        migrations.CreateModel(
            name='FileProcessingJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('virus_scan', 'Virus Scanning'), ('thumbnail_generation', 'Thumbnail Generation'), ('content_analysis', 'Content Analysis'), ('text_extraction', 'Text Extraction'), ('format_conversion', 'Format Conversion'), ('backup', 'Backup Creation')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in seconds', null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='file_handler.fileupload')),
            ],
            options={
                'verbose_name': 'File Processing Job',
                'verbose_name_plural': 'File Processing Jobs',
            },
        ),
        migrations.CreateModel(
            name='FileBackup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_type', models.CharField(choices=[('automatic', 'Automatic Backup'), ('manual', 'Manual Backup'), ('archive', 'Archive Backup')], max_length=20)),
                ('backup_path', models.CharField(help_text='Path to backup location', max_length=500)),
                ('backup_size', models.BigIntegerField()),
                ('backup_location', models.CharField(help_text='Storage location (local, s3, etc.)', max_length=100)),
                ('backup_hash', models.CharField(max_length=64)),
                ('compression_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='file_handler.fileupload')),
            ],
            options={
                'verbose_name': 'File Backup',
                'verbose_name_plural': 'File Backups',
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file_path', models.FileField(upload_to='versions/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('change_description', models.TextField(blank=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='file_handler.fileupload')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Version',
                'verbose_name_plural': 'File Versions',
            },
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['uploaded_by'], name='file_handle_uploade_720876_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['status'], name='file_handle_status_1fe446_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_category'], name='file_handle_file_ca_5e0d27_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['virus_scan_result'], name='file_handle_virus_s_a0dcd9_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['created_at'], name='file_handle_created_373556_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['expires_at'], name='file_handle_expires_857638_idx'),
        ),
        migrations.AddIndex(
            model_name='filethumbnail',
            index=models.Index(fields=['original_file'], name='file_handle_origina_8a6405_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filethumbnail',
            unique_together={('original_file', 'size_type')},
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['file'], name='file_handle_file_id_922b96_idx'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['shared_by'], name='file_handle_shared__e6f9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['shared_with'], name='file_handle_shared__c25685_idx'),
        ),
        migrations.AddIndex(
            model_name='fileshare',
            index=models.Index(fields=['share_token'], name='file_handle_share_t_258304_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['file'], name='file_handle_file_id_5265cf_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['job_type'], name='file_handle_job_typ_e77652_idx'),
        ),
        migrations.AddIndex(
            model_name='fileprocessingjob',
            index=models.Index(fields=['status'], name='file_handle_status_0cc7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='filebackup',
            index=models.Index(fields=['original_file'], name='file_handle_origina_4b9d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='filebackup',
            index=models.Index(fields=['backup_type'], name='file_handle_backup__0312b4_idx'),
        ),
        migrations.AddIndex(
            model_name='fileversion',
            index=models.Index(fields=['original_file', 'version_number'], name='file_handle_origina_18ea97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together={('original_file', 'version_number')},
        ),
    ]
