# Generated by Django 5.0.14 on 2025-08-02 03:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_requests', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('search_radius', models.IntegerField(default=50, help_text='Search radius in kilometers', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quote_type', models.CharField(choices=[('standard', 'Standard Quote'), ('bulk_discount', 'Bulk Discount'), ('custom_pricing', 'Custom Pricing'), ('negotiable', 'Negotiable'), ('fixed_price', 'Fixed Price')], default='standard', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_quoted', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('delivery_method', models.CharField(choices=[('pickup', 'Customer Pickup'), ('delivery', 'Supplier Delivery'), ('shipping', 'Third-party Shipping'), ('digital', 'Digital Delivery')], default='delivery', max_length=20)),
                ('estimated_delivery_days', models.IntegerField(default=7, help_text='Estimated delivery time in days', validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_terms', models.TextField(blank=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Quote validity expiration', null=True)),
                ('payment_terms', models.CharField(default='Net 30', help_text='Payment terms (e.g., Net 30, COD, etc.)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired'), ('draft', 'Draft')], default='pending', max_length=20)),
                ('is_best_price', models.BooleanField(default=False)),
                ('rank_position', models.IntegerField(blank=True, null=True)),
                ('viewed_by_requester', models.BooleanField(default=False)),
                ('requester_view_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='products.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='product_requests.productrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quotes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotes/attachments/')),
                ('filename', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.quote')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quotes', models.IntegerField(default=0)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('highest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comparison_data', models.JSONField(default=dict, help_text='Detailed comparison analysis')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('best_delivery_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_delivery_comparisons', to='quotes.quote')),
                ('best_price_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_price_comparisons', to='quotes.quote')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_comparison', to='product_requests.productrequest')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('clarification', 'Clarification'), ('negotiation', 'Negotiation'), ('revision', 'Revision Request'), ('acceptance', 'Acceptance'), ('rejection', 'Rejection'), ('system', 'System Message')], default='clarification', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal messages not visible to other party')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quotes.quote')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_quote_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['request', 'status'], name='quotes_quot_request_e9d29d_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['supplier', 'status'], name='quotes_quot_supplie_f9a395_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status', 'valid_until'], name='quotes_quot_status_3ae330_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['reference_number'], name='quotes_quot_referen_9b3694_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['unit_price'], name='quotes_quot_unit_pr_b4e140_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('request', 'supplier')},
        ),
        migrations.AddIndex(
            model_name='quotecomparison',
            index=models.Index(fields=['request'], name='quotes_quot_request_b50574_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['quote', 'sort_order'], name='quotes_quot_quote_i_474c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='quotemessage',
            index=models.Index(fields=['quote', 'created_at'], name='quotes_quot_quote_i_7a8977_idx'),
        ),
        migrations.AddIndex(
            model_name='quotemessage',
            index=models.Index(fields=['sender'], name='quotes_quot_sender__c13da6_idx'),
        ),
    ]
