# Generated by Django 5.0.14 on 2025-08-09 12:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerElectronics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('electronics_type', models.CharField(choices=[('WASHING_MACHINE', 'Washing Machine'), ('REFRIGERATOR', 'Refrigerator'), ('TELEVISION', 'Television'), ('MICROWAVE', 'Microwave'), ('AIR_CONDITIONER', 'Air Conditioner'), ('DISHWASHER', 'Dishwasher'), ('DRYER', 'Dryer'), ('OVEN', 'Oven'), ('VACUUM_CLEANER', 'Vacuum Cleaner'), ('BLENDER', 'Blender'), ('COFFEE_MAKER', 'Coffee Maker'), ('TOASTER', 'Toaster'), ('IRON', 'Iron'), ('HAIR_DRYER', 'Hair Dryer'), ('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop Computer'), ('SMARTPHONE', 'Smartphone'), ('TABLET', 'Tablet'), ('PRINTER', 'Printer'), ('CAMERA', 'Camera'), ('SPEAKER', 'Speaker'), ('HEADPHONES', 'Headphones'), ('GAMING_CONSOLE', 'Gaming Console'), ('OTHER', 'Other')], help_text='Type of electronic product needed', max_length=30)),
                ('brand_preference', models.CharField(blank=True, help_text='Preferred brand (e.g., Samsung, LG, Apple)', max_length=100)),
                ('model_series', models.CharField(blank=True, help_text='Specific model or series if known', max_length=100)),
                ('quantity_needed', models.IntegerField(help_text='How many units needed?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='ZAR', help_text='Currency code', max_length=3)),
                ('urgency', models.CharField(choices=[('ASAP', 'ASAP'), ('WITHIN_WEEK', 'Within a week'), ('WITHIN_MONTH', 'Within a month'), ('FLEXIBLE', 'Flexible')], help_text='How soon do you need the product?', max_length=20)),
                ('installation_required', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', help_text='Do you need installation services?', max_length=3)),
                ('required_features', models.TextField(blank=True, help_text='Required features or specifications (e.g., capacity, energy rating, etc.)')),
                ('condition_preference', models.CharField(choices=[('NEW', 'New'), ('REFURBISHED', 'New / Refurbished'), ('USED', 'Used'), ('ANY', 'Any Condition')], default='NEW', help_text='Preferred condition of the product', max_length=20)),
                ('purpose_of_purchase', models.CharField(choices=[('HOME_USE', 'Home Use'), ('OFFICE_USE', 'Office Use'), ('COMMERCIAL_USE', 'Commercial Use'), ('PERSONAL_USE', 'Personal Use'), ('BUSINESS_USE', 'Business Use'), ('EDUCATIONAL', 'Educational'), ('OTHER', 'Other')], help_text='What will this product be used for?', max_length=20)),
                ('additional_comments', models.TextField(blank=True, help_text='Any additional requirements or comments')),
                ('product_images', models.JSONField(blank=True, help_text='Array of uploaded product image URLs or documents', null=True)),
                ('delivery_location', models.JSONField(blank=True, help_text='Delivery or pickup location information', null=True)),
                ('warranty_required', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', help_text='Do you require warranty coverage?', max_length=3)),
                ('warranty_duration', models.CharField(blank=True, help_text='Preferred warranty duration (e.g., 1 year, 2 years)', max_length=50)),
                ('energy_efficiency_required', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', help_text='Is energy efficiency important? (A+ rating or higher)', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consumer_electronics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['electronics_type'], name='consumer_el_electro_589e57_idx'), models.Index(fields=['brand_preference'], name='consumer_el_brand_p_400bb9_idx'), models.Index(fields=['urgency'], name='consumer_el_urgency_9c4f3b_idx'), models.Index(fields=['condition_preference'], name='consumer_el_conditi_76da39_idx'), models.Index(fields=['purpose_of_purchase'], name='consumer_el_purpose_acba1b_idx'), models.Index(fields=['created_at'], name='consumer_el_created_6a43a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('VEHICLE_SPARES', 'Vehicle Spares'), ('TYRES_RIMS', 'Tyres & Rims'), ('ELECTRONICS', 'Electronics')], max_length=20)),
                ('title', models.CharField(help_text='Auto-generated from specifications', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Buyer-provided product description', null=True)),
                ('product_specifications', models.JSONField(help_text='Category-specific specifications')),
                ('quantity', models.IntegerField(help_text='Required quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('condition_preference', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished'), ('ANY', 'Any')], default='ANY', max_length=20)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget limit', max_digits=12, null=True)),
                ('currency', models.CharField(default='ZAR', help_text='Currency code', max_length=3)),
                ('buyer_location', models.JSONField(help_text='Lat/lng and address details')),
                ('max_travel_distance', models.IntegerField(default=50, help_text='Maximum distance willing to travel (km)')),
                ('urgency_timeline', models.CharField(choices=[('ASAP', 'ASAP'), ('12_HOURS', '12 Hours'), ('1_WEEK', '1 Week'), ('1_MONTH', '1 Month')], help_text='ASAP, 12 Hours, 1 Week, 1 Month, etc.', max_length=50)),
                ('product_images', models.JSONField(blank=True, help_text='Array of uploaded image URLs', null=True)),
                ('vin_photo_url', models.CharField(blank=True, help_text='VIN photo for vehicle spares', max_length=500, null=True)),
                ('terms_accepted', models.BooleanField(help_text='Must accept terms and conditions')),
                ('contact_consent', models.BooleanField(help_text='Consent to be contacted for quotes')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Auto-calculated based on urgency', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('view_count', models.IntegerField(default=0, help_text='Number of views by sellers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to=settings.AUTH_USER_MODEL)),
                ('consumer_electronics', models.ForeignKey(blank=True, help_text='Detailed consumer electronics specifications if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='product_requests.consumerelectronics')),
            ],
            options={
                'db_table': 'product_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='requests/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_requests.productrequest')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSpares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_make', models.CharField(help_text='Vehicle manufacturer (e.g., Toyota, Ford)', max_length=50)),
                ('vehicle_model', models.CharField(help_text='Vehicle model (e.g., Corolla, Focus)', max_length=50)),
                ('vehicle_year', models.IntegerField(help_text='Manufacturing year of the vehicle', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2030)])),
                ('vehicle_type', models.CharField(choices=[('PASSENGER_CAR', 'Passenger Car'), ('SUV', 'SUV'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('TRAILER', 'Trailer'), ('VAN', 'Van'), ('BUS', 'Bus')], help_text='Type of vehicle', max_length=20)),
                ('engine_size', models.CharField(blank=True, help_text='Engine size/displacement (e.g., 1.6L, 2000cc)', max_length=20)),
                ('vin_number', models.CharField(blank=True, help_text='Vehicle Identification Number (optional)', max_length=17)),
                ('part_name', models.CharField(help_text='Name or description of the required part', max_length=100)),
                ('part_category', models.CharField(choices=[('ENGINE', 'Engine Parts'), ('TRANSMISSION', 'Transmission'), ('BRAKES', 'Brake System'), ('SUSPENSION', 'Suspension'), ('ELECTRICAL', 'Electrical'), ('BODY', 'Body Parts'), ('INTERIOR', 'Interior'), ('EXHAUST', 'Exhaust System'), ('COOLING', 'Cooling System'), ('FUEL', 'Fuel System'), ('OTHER', 'Other')], help_text='Category of the spare part', max_length=20)),
                ('part_number', models.CharField(blank=True, help_text='Manufacturer part number (if known)', max_length=50)),
                ('quantity', models.IntegerField(help_text='How many pieces needed?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('condition_preference', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished'), ('REMANUFACTURED', 'Remanufactured')], default='NEW', help_text='Preferred condition of the part', max_length=20)),
                ('urgency', models.CharField(choices=[('ASAP', 'ASAP'), ('12_HOURS', '12 Hours'), ('24_HOURS', '24 Hours'), ('1_WEEK', '1 Week'), ('1_MONTH', '1 Month')], help_text='How soon do you need this part?', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional description or specific requirements')),
                ('compatible_models', models.TextField(blank=True, help_text='Other vehicle models this part might fit')),
                ('preferred_brand', models.CharField(blank=True, help_text='Preferred brand(s) - can list multiple', max_length=100)),
                ('avoid_brands', models.CharField(blank=True, help_text='Brands to avoid (if any)', max_length=100)),
                ('installation_required', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', help_text='Do you need installation service?', max_length=3)),
                ('warranty_required', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', help_text='Do you require warranty on the part?', max_length=3)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget for this part', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='ZAR', help_text='Currency code', max_length=3)),
                ('product_images', models.JSONField(blank=True, help_text='Array of uploaded product image URLs', null=True)),
                ('vin_photo', models.URLField(blank=True, help_text='VIN plate photo URL')),
                ('location_info', models.JSONField(blank=True, help_text='Location information for pickup or delivery', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_spares',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle_make', 'vehicle_model'], name='vehicle_spa_vehicle_c62cac_idx'), models.Index(fields=['part_category'], name='vehicle_spa_part_ca_ec558a_idx'), models.Index(fields=['urgency'], name='vehicle_spa_urgency_72a2b7_idx'), models.Index(fields=['condition_preference'], name='vehicle_spa_conditi_7b954e_idx'), models.Index(fields=['created_at'], name='vehicle_spa_created_66a800_idx')],
            },
        ),
        migrations.AddField(
            model_name='productrequest',
            name='vehicle_spares',
            field=models.ForeignKey(blank=True, help_text='Detailed vehicle spares specifications if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='product_requests.vehiclespares'),
        ),
        migrations.CreateModel(
            name='VehicleTyresRims',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tyre_width', models.IntegerField(help_text='Tyre width in millimeters (e.g., 205)', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(500)])),
                ('sidewall_profile', models.CharField(choices=[('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70')], help_text='Sidewall profile (e.g., 55)', max_length=3)),
                ('wheel_rim_diameter', models.CharField(choices=[('13', '13"'), ('14', '14"'), ('15', '15"'), ('16', '16"'), ('17', '17"'), ('18', '18"'), ('19', '19"'), ('20', '20"'), ('21', '21"'), ('22', '22"')], help_text='Wheel rim diameter in inches', max_length=2)),
                ('select_tyres_rims', models.CharField(choices=[('TYRES', 'Tyres'), ('RIMS', 'Rims'), ('BOTH', 'Both Tyres and Rims')], help_text='What are you looking for?', max_length=20)),
                ('quantity', models.IntegerField(help_text='How many pieces needed?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('urgency', models.CharField(choices=[('ASAP', 'ASAP'), ('12_HOURS', '12 Hours'), ('24_HOURS', '24 Hours'), ('1_WEEK', '1 Week'), ('1_MONTH', '1 Month')], help_text='How soon do you need to buy this product?', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the item needed')),
                ('vehicle_type', models.CharField(choices=[('PASSENGER_CAR', 'Passenger Car'), ('SUV', 'SUV'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('TRAILER', 'Trailer')], help_text='Type of vehicle', max_length=20)),
                ('pitch_circle_diameter', models.CharField(blank=True, help_text='PCD measurement (e.g., 5x100)', max_length=10)),
                ('preferred_brand', models.CharField(blank=True, help_text='Preferred brand(s) - can list multiple', max_length=100)),
                ('tyre_construction_type', models.CharField(blank=True, choices=[('RADIAL', 'Radial'), ('BIAS', 'Bias'), ('BELTED_BIAS', 'Belted Bias')], help_text='Construction type preference', max_length=20)),
                ('balancing_required', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', help_text='Do you need balancing service?', max_length=3)),
                ('tyre_rotation_required', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', help_text='Do you need tyre rotation service?', max_length=3)),
                ('fitment_required', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', help_text='Do you need fitment service?', max_length=3)),
                ('product_images', models.JSONField(blank=True, help_text='Array of uploaded product image URLs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_tyres_rims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['select_tyres_rims'], name='vehicle_tyr_select__226d65_idx'), models.Index(fields=['vehicle_type'], name='vehicle_tyr_vehicle_a2d834_idx'), models.Index(fields=['urgency'], name='vehicle_tyr_urgency_b91aa1_idx'), models.Index(fields=['created_at'], name='vehicle_tyr_created_5542bf_idx')],
            },
        ),
        migrations.AddField(
            model_name='productrequest',
            name='vehicle_tyres_rims',
            field=models.ForeignKey(blank=True, help_text='Detailed tyres and rims specifications if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to='product_requests.vehicletyresrims'),
        ),
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('inquiry', 'Inquiry'), ('clarification', 'Clarification'), ('update', 'Update'), ('quote_submission', 'Quote Submission'), ('system', 'System Message')], default='inquiry', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal messages not visible to requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='product_requests.productrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_request_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='product_req_request_3606ae_idx'), models.Index(fields=['sender'], name='product_req_sender__742078_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product_requests.productrequest')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('request', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('request_type', models.CharField(max_length=30)),
                ('template_data', models.JSONField(default=dict, help_text='JSON data for pre-filling request forms')),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_templates', to='categories.category')),
            ],
            options={
                'ordering': ['category__name', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='product_req_categor_4d724f_idx'), models.Index(fields=['request_type', 'is_active'], name='product_req_request_c78899_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_on_quotes', models.BooleanField(default=True)),
                ('notify_on_updates', models.BooleanField(default=True)),
                ('notify_on_messages', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='product_requests.productrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='product_req_user_id_6898b0_idx')],
                'unique_together': {('request', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['status', 'category'], name='product_req_status_aa566b_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['buyer_id', 'status'], name='product_req_buyer_i_a82346_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['category', 'status'], name='product_req_categor_d57c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['expiry_date'], name='product_req_expiry__bd7b48_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['urgency_timeline'], name='product_req_urgency_a3c9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['created_at'], name='product_req_created_19e00b_idx'),
        ),
    ]
