# Generated by Django 5.0.14 on 2025-08-10 03:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('service_down', 'Service Down'), ('high_error_rate', 'High Error Rate'), ('slow_response', 'Slow Response Time'), ('queue_backlog', 'Queue Backlog'), ('resource_exhaustion', 'Resource Exhaustion'), ('external_service_failure', 'External Service Failure'), ('custom', 'Custom Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_component', models.CharField(blank=True, max_length=100)),
                ('source_check', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], default='active', max_length=20)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('notifications_sent', models.PositiveIntegerField(default=0)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('alert_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'severity'], name='health_moni_alert_t_ea9e87_idx'), models.Index(fields=['status', '-created_at'], name='health_moni_status_369f03_idx'), models.Index(fields=['source_component'], name='health_moni_source__d5a94e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComponentHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('database', 'Database'), ('queue', 'Message Queue'), ('email_service', 'Email Service'), ('sms_service', 'SMS Service'), ('push_service', 'Push Notification Service'), ('webhook_service', 'Webhook Service'), ('api_endpoint', 'API Endpoint'), ('background_worker', 'Background Worker'), ('cache', 'Cache'), ('external_api', 'External API')], max_length=50)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown')], max_length=20)),
                ('response_time_ms', models.FloatField(default=0.0)),
                ('success_rate_percentage', models.FloatField(default=100.0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_check_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['component_name'],
                'indexes': [models.Index(fields=['component_type', 'status'], name='health_moni_compone_ba5f49_idx'), models.Index(fields=['status', '-last_check_at'], name='health_moni_status_4dfc45_idx')],
                'unique_together': {('component_name', 'component_type')},
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_name', models.CharField(max_length=100)),
                ('check_type', models.CharField(choices=[('ping', 'Ping Test'), ('database', 'Database Connection'), ('queue', 'Queue Connectivity'), ('email', 'Email Service'), ('sms', 'SMS Service'), ('push', 'Push Service'), ('webhook', 'Webhook Service'), ('disk_space', 'Disk Space'), ('memory', 'Memory Usage'), ('cpu', 'CPU Usage'), ('custom', 'Custom Check')], max_length=50)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warn', 'Warning')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('expected_value', models.CharField(blank=True, max_length=200)),
                ('actual_value', models.CharField(blank=True, max_length=200)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['check_name', '-executed_at'], name='health_moni_check_n_3eba2a_idx'), models.Index(fields=['status', '-executed_at'], name='health_moni_status_345be1_idx'), models.Index(fields=['check_type'], name='health_moni_check_t_a392ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone_name', models.CharField(default='UTC', max_length=50)),
                ('maintenance_type', models.CharField(choices=[('planned', 'Planned Maintenance'), ('emergency', 'Emergency Maintenance'), ('upgrade', 'System Upgrade'), ('patch', 'Security Patch')], max_length=50)),
                ('affected_components', models.JSONField(default=list, help_text='List of affected components')),
                ('impact_level', models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact'), ('full_outage', 'Full Outage')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notify_users', models.BooleanField(default=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='health_moni_start_t_ff717f_idx'), models.Index(fields=['status'], name='health_moni_status_274831_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('maintenance', 'Under Maintenance')], default='healthy', max_length=20)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('response_time_ms', models.FloatField(default=0.0)),
                ('error_rate_percentage', models.FloatField(default=0.0)),
                ('cpu_usage_percentage', models.FloatField(default=0.0)),
                ('memory_usage_percentage', models.FloatField(default=0.0)),
                ('disk_usage_percentage', models.FloatField(default=0.0)),
                ('queue_size', models.PositiveIntegerField(default=0)),
                ('oldest_message_age_minutes', models.FloatField(default=0.0)),
                ('processing_rate_per_minute', models.FloatField(default=0.0)),
                ('db_connection_pool_usage', models.FloatField(default=0.0)),
                ('db_response_time_ms', models.FloatField(default=0.0)),
                ('external_service_failures', models.PositiveIntegerField(default=0)),
                ('last_check_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_duration_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='health_moni_status_922e8c_idx'), models.Index(fields=['-created_at'], name='health_moni_created_b0670f_idx')],
            },
        ),
    ]
