# Generated by Django 5.0.14 on 2025-08-10 02:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(help_text='ISO 4217 currency code', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('is_base_currency', models.BooleanField(default=False, help_text='Base currency for exchange rate calculations')),
                ('is_supported', models.BooleanField(default=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Gateway name', max_length=100)),
                ('slug', models.SlugField(help_text='Gateway slug for API reference', unique=True)),
                ('config', models.JSONField(default=dict, help_text='Gateway configuration including API keys')),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('public_key', models.TextField(blank=True, help_text='Public/Publishable Key', null=True)),
                ('secret_key', models.TextField(blank=True, help_text='Secret/Private Key', null=True)),
                ('webhook_secret', models.TextField(blank=True, help_text='Webhook verification secret', null=True)),
                ('base_url', models.URLField(blank=True, help_text='Gateway API base URL', null=True)),
                ('callback_url', models.URLField(blank=True, help_text='Payment callback URL', null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook notification URL', null=True)),
                ('supports_escrow', models.BooleanField(default=False)),
                ('supports_refunds', models.BooleanField(default=True)),
                ('supports_webhooks', models.BooleanField(default=True)),
                ('supports_subscriptions', models.BooleanField(default=False)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.01, max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=4, default=0.015, max_digits=5)),
                ('fixed_transaction_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('supported_currencies', models.JSONField(default=list, help_text='List of supported currency codes')),
                ('supported_countries', models.JSONField(default=list, help_text='List of supported country codes')),
                ('additional_config', models.JSONField(default=dict, help_text='Additional gateway-specific configuration')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'db_table': 'payment_gateways',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system_managed', models.BooleanField(default=True, help_text='Managed by system, not editable by users')),
                ('category', models.CharField(default='general', max_length=50)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'system_configurations',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='identity_documents/')),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('pin_attempts', models.IntegerField(default=0)),
                ('pin_locked_until', models.DateTimeField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('total_transactions', models.IntegerField(default=0)),
                ('successful_transactions', models.IntegerField(default=0)),
                ('total_amount_transacted', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
