name: bidr
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  just_audio: ^0.9.46
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  geocoding: ^2.1.1
  shared_preferences: ^2.5.2
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  motion_toast: ^2.11.0
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  #wakelock_web: ^1.3.1
  animate_do: ^4.2.0
  permission_handler: ^11.4.0
  go_router: ^14.8.1
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  flutter_paystack_plus: ^2.2.1
  smooth_page_indicator: ^1.2.1
  encrypt: ^5.0.3
  page_animation_transition: ^1.0.0
  rive_animated_icon: ^2.0.3
  cupertino_calendar_picker: ^2.2.2
  hugeicons: ^0.0.7
  dropdown_button2: ^2.3.9
  file_picker: ^8.1.4
  google_maps_flutter: ^2.10.1
  jitsi_meet_flutter_sdk: ^11.1.1
  uuid: ^4.2.1
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.3
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^4.0.0
  fl_chart: ^1.0.0
  video_player: ^2.8.0  # Downgrade to compatible version
  url_launcher: ^6.3.1
  chewie: ^1.7.5
  flutter_chatflow: ^2.0.2
  gradient_borders: ^1.0.1
  gradient_glow_border: ^1.0.3
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/bidr_logo.png
    - lib/assets/images/sample.jpg
    - lib/assets/images/bidr_logo1.png
    - lib/assets/images/bidr_logo2.png
    - lib/assets/images/competitive.png
    - lib/assets/images/electronics.png
    - lib/assets/images/facebook.png
    - lib/assets/images/instagram.png
    - lib/assets/images/mask_group.png
    - lib/assets/images/twitter.png
    - lib/assets/images/tyres_rims.png
    - lib/assets/images/consumer.png
    - lib/assets/images/rims.png
    - lib/assets/images/vehicle_spares.png
    - lib/assets/images/spares1.png
    - lib/assets/images/youTube.png
    - lib/assets/images/buyer.png
    - lib/assets/images/business.png
    - lib/assets/images/auto_spares.png
    - lib/assets/images/electronics_com.png
    - lib/assets/images/rims_and_tyre.png
    - lib/assets/images/contact.png
    - lib/assets/images/bag_logo.png
    - lib/assets/images/pay_image.png
    - lib/assets/images/absa.png
    - lib/assets/images/American-Express.png
    - lib/assets/images/DinnersClub.png
    - lib/assets/images/GPay.png
    - lib/assets/images/Maestro.png
    - lib/assets/images/Mastercard.png
    - lib/assets/images/mobi.png
    - lib/assets/images/nedbank.png
    - lib/assets/images/SamsungPay.png
    - lib/assets/images/sid.png
    - lib/assets/images/snapscan.png
    - lib/assets/images/standard.png
    - lib/assets/images/Visa.png
    - lib/assets/images/visa2.png
    - lib/assets/images/zapper.png
    - lib/assets/images/applePay.png
    - lib/assets/images/share.png
    - lib/assets/images/confirmed.png
    - lib/assets/images/rejected.png
    - lib/assets/svgs/bidr_logo_with_text.svg
    - lib/assets/covers/Group 1171275363.png
    - lib/assets/images/bidr_logo_with_text.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #    - family: Manrope
  #      fonts:
  #        - asset: assets/fonts/Manrope-Regular.ttf
  #        - asset: assets/fonts/Manrope-Bold.ttf
  #          weight: 700
  #        - asset: assets/fonts/Manrope-SemiBold.ttf
  #          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
