# Generated by Django 5.0.14 on 2025-09-07 05:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequestAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(help_text='Date this analytics record represents')),
                ('timeframe', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('unique_views', models.IntegerField(default=0, help_text='Number of unique views')),
                ('search_appearances', models.IntegerField(default=0, help_text='Times request appeared in search results')),
                ('search_clicks', models.IntegerField(default=0, help_text='Times request was clicked from search results')),
                ('quote_responses', models.IntegerField(default=0, help_text='Number of quote responses received')),
                ('messages_sent', models.IntegerField(default=0, help_text='Number of messages sent to requestor')),
                ('watchlist_additions', models.IntegerField(default=0, help_text='Number of times added to watchlist')),
                ('average_response_time', models.DurationField(blank=True, help_text='Average response time for quotes', null=True)),
                ('supplier_interest_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Score based on supplier engagement (0-100)', max_digits=5)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('timeframe', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_units_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_units_per_order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_quotes', models.IntegerField(default=0)),
                ('accepted_quotes', models.IntegerField(default=0)),
                ('quote_acceptance_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('query', models.CharField(help_text='The search query', max_length=500)),
                ('query_hash', models.CharField(help_text='Hash of the query for grouping', max_length=64)),
                ('date', models.DateField()),
                ('search_count', models.IntegerField(default=1, help_text='Number of times this query was searched')),
                ('results_count', models.IntegerField(default=0, help_text='Number of results returned')),
                ('clicks', models.IntegerField(default=0, help_text='Number of clicks on results')),
                ('average_position_clicked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average position of clicked results', max_digits=5)),
                ('zero_results', models.BooleanField(default=False, help_text='Whether this query returned zero results')),
            ],
            options={
                'ordering': ['-search_count', '-date'],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('timeframe', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('returning_users', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_pageviews', models.IntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, help_text='Average session duration', null=True)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bounce rate percentage', max_digits=5)),
                ('users_with_requests', models.IntegerField(default=0, help_text='Users who made at least one request')),
                ('users_with_quotes', models.IntegerField(default=0, help_text='Users who submitted at least one quote')),
                ('users_with_orders', models.IntegerField(default=0, help_text='Users who made at least one order')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('product_performance', 'Product Performance'), ('sales_summary', 'Sales Summary'), ('inventory_status', 'Inventory Status'), ('user_behavior', 'User Behavior'), ('search_analysis', 'Search Analysis'), ('category_performance', 'Category Performance'), ('custom', 'Custom Report')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired'), ('draft', 'Draft')], default='pending', max_length=20)),
                ('report_data', models.JSONField(default=dict, help_text='Generated report data')),
                ('file_path', models.CharField(blank=True, help_text='Path to generated report file', max_length=500)),
                ('file_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], default='json', max_length=10)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters used to generate the report')),
                ('generation_time', models.DurationField(blank=True, help_text='Time taken to generate the report', null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('timeframe', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('total_requests', models.IntegerField(default=0, help_text='Total number of product requests in category')),
                ('active_requests', models.IntegerField(default=0, help_text='Number of active product requests')),
                ('new_requests', models.IntegerField(default=0, help_text='New product requests added in this period')),
                ('closed_requests', models.IntegerField(default=0, help_text='Number of closed requests in this period')),
                ('total_views', models.IntegerField(default=0)),
                ('total_quote_requests', models.IntegerField(default=0)),
                ('total_quotes', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average product price in category', max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average product rating in category', max_digits=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='categories.category')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('timeframe', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('total_products', models.IntegerField(default=0, help_text='Total number of products')),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total value of inventory', max_digits=12)),
                ('total_units', models.IntegerField(default=0, help_text='Total number of units in stock')),
                ('in_stock_products', models.IntegerField(default=0, help_text='Number of products in stock')),
                ('out_of_stock_products', models.IntegerField(default=0, help_text='Number of products out of stock')),
                ('low_stock_products', models.IntegerField(default=0, help_text='Number of products with low stock')),
                ('units_received', models.IntegerField(default=0, help_text='Units added to inventory')),
                ('units_sold', models.IntegerField(default=0, help_text='Units sold from inventory')),
                ('units_adjusted', models.IntegerField(default=0, help_text='Units adjusted (positive or negative)')),
                ('inventory_turnover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Inventory turnover ratio', max_digits=8)),
                ('days_of_inventory', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Days of inventory remaining', max_digits=8)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'timeframe'], name='analytics_i_date_ffdea5_idx')],
                'unique_together': {('date', 'timeframe')},
            },
        ),
    ]
