# Generated by Django 5.0.14 on 2025-09-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('categories', '0001_initial'),
        ('product_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequestanalytics',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='product_requests.productrequest'),
        ),
        migrations.AddField(
            model_name='salesanalytics',
            name='top_category',
            field=models.ForeignKey(blank=True, help_text='Top performing category by revenue', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['query_hash', 'date'], name='analytics_s_query_h_b95387_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['date', 'search_count'], name='analytics_s_date_c4f31f_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['zero_results', 'date'], name='analytics_s_zero_re_8cc1ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='searchanalytics',
            unique_together={('query_hash', 'date')},
        ),
        migrations.AddIndex(
            model_name='userbehavioranalytics',
            index=models.Index(fields=['date', 'timeframe'], name='analytics_u_date_3af805_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbehavioranalytics',
            unique_together={('date', 'timeframe')},
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['report_type', 'status'], name='analytics_a_report__858af4_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['generated_by', 'created_at'], name='analytics_a_generat_de0dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['start_date', 'end_date'], name='analytics_a_start_d_7aaa8a_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryanalytics',
            index=models.Index(fields=['category', 'date'], name='analytics_c_categor_910f31_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryanalytics',
            index=models.Index(fields=['date', 'timeframe'], name='analytics_c_date_91409d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryanalytics',
            unique_together={('category', 'date', 'timeframe')},
        ),
        migrations.AddIndex(
            model_name='productrequestanalytics',
            index=models.Index(fields=['request', 'date'], name='analytics_p_request_87f8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequestanalytics',
            index=models.Index(fields=['date', 'timeframe'], name='analytics_p_date_57d045_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequestanalytics',
            index=models.Index(fields=['supplier_interest_score', 'date'], name='analytics_p_supplie_c22fbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrequestanalytics',
            unique_together={('request', 'date', 'timeframe')},
        ),
        migrations.AddIndex(
            model_name='salesanalytics',
            index=models.Index(fields=['date', 'timeframe'], name='analytics_s_date_e136fb_idx'),
        ),
        migrations.AddIndex(
            model_name='salesanalytics',
            index=models.Index(fields=['total_revenue', 'date'], name='analytics_s_total_r_a140bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesanalytics',
            unique_together={('date', 'timeframe')},
        ),
    ]
