# Generated by Django 5.1.11 on 2025-08-29 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyers_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
                'db_table': 'buyer',
            },
        ),
        migrations.CreateModel(
            name='BuyersAddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('postal_address', models.TextField(blank=True, help_text='Street number of the address.', max_length=10, null=True)),
                ('physical_address', models.TextField(help_text='Street name of the address.', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Suburb or neighborhood of the address.', max_length=100, null=True)),
                ('contact_person_name', models.CharField(help_text='City of the address.', max_length=100)),
                ('contact_person_telephone', models.CharField(help_text='Province or state of the address.', max_length=100)),
                ('contact_person_email_address', models.CharField(help_text='Postal code or ZIP code of the address.', max_length=10)),
                ('platform_workflow_email_address', models.CharField(default='South Africa', help_text='Country of the address.', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Indicates the primary address.')),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user or account this address belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='address_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyers Address Detail',
                'verbose_name_plural': 'Buyers Address Details',
                'db_table': 'buyers_address_details',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_address_per_buyerr')],
            },
        ),
    ]
