# Generated by Django 5.1.11 on 2025-09-04 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_appuser_buyer_quote_seller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Dispute identifier', primary_key=True, serialize=False)),
                ('dispute_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('DELIVERY', 'Delivery'), ('QUALITY', 'Quality'), ('OTHER', 'Other')], help_text="'PAYMENT', 'DELIVERY', 'QUALITY', 'OTHER'", max_length=20)),
                ('description', models.TextField(help_text='Dispute description')),
                ('evidence_files', models.JSONField(blank=True, help_text='Supporting evidence', null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', help_text="'OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED'", max_length=20)),
                ('resolution', models.TextField(blank=True, help_text='Resolution details', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Resolution date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modified')),
                ('initiator_id', models.ForeignKey(help_text='Reference to Users.user_id', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Reference to admin Users.user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction_id', models.ForeignKey(help_text='Reference to Transactions.transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='disputes_di_transac_33431b_idx'), models.Index(fields=['initiator_id'], name='disputes_di_initiat_1aa68f_idx'), models.Index(fields=['dispute_type'], name='disputes_di_dispute_f4c772_idx'), models.Index(fields=['status'], name='disputes_di_status_124397_idx'), models.Index(fields=['resolved_at'], name='disputes_di_resolve_cdf7f4_idx')],
            },
        ),
    ]
