# Generated by Django 5.1.11 on 2025-09-04 03:37

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dispute',
            name='disputes_di_transac_33431b_idx',
        ),
        migrations.RemoveIndex(
            model_name='dispute',
            name='disputes_di_initiat_1aa68f_idx',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='initiator_id',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='dispute',
            name='buyer_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Reference to buyer user UUID (formerly initiator_id)'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Reference to request UUID (formerly transaction_id)'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='seller_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Reference to seller user UUID'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['request_id'], name='disputes_di_request_48cbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['buyer_id'], name='disputes_di_buyer_i_723775_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['seller_id'], name='disputes_di_seller__47e0c7_idx'),
        ),
    ]
