# Generated by Django 5.0.14 on 2025-08-10 00:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('image', 'Image'), ('file', 'File Attachment'), ('audio', 'Audio Message'), ('video', 'Video'), ('location', 'Location'), ('contact', 'Contact Info'), ('quote', 'Quote/Bid'), ('system', 'System Message'), ('notification', 'Notification')], default='text', max_length=20)),
                ('content', models.TextField(help_text='Main message content')),
                ('original_content', models.TextField(blank=True, help_text='Original content before moderation')),
                ('thread_id', models.UUIDField(blank=True, help_text='Thread identifier for grouped messages', null=True)),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.TextField(blank=True)),
                ('is_auto_moderated', models.BooleanField(default=False)),
                ('moderation_action', models.CharField(blank=True, max_length=50)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encryption_key_id', models.CharField(blank=True, max_length=100)),
                ('reaction_count', models.PositiveIntegerField(default=0)),
                ('client_message_id', models.CharField(blank=True, help_text='Client-side message ID', max_length=100)),
                ('message_hash', models.CharField(blank=True, help_text='Content hash for deduplication', max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_conversations.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat_messaging.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image/video width', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image/video height', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Audio/video duration in seconds', null=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('scan_result', models.CharField(blank=True, choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('malicious', 'Malicious'), ('error', 'Scan Error')], max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash of file', max_length=64)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat_messaging.message')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageDeletion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deletion_reason', models.CharField(choices=[('user_requested', 'User Requested'), ('moderation', 'Content Moderation'), ('admin_action', 'Admin Action'), ('system_cleanup', 'System Cleanup'), ('privacy_request', 'Privacy Request')], max_length=30)),
                ('deletion_details', models.TextField(blank=True)),
                ('content_snapshot', models.TextField(help_text='Snapshot of message content at deletion')),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='chat_messaging.message')),
            ],
            options={
                'verbose_name': 'Message Deletion',
                'verbose_name_plural': 'Message Deletions',
            },
        ),
        migrations.CreateModel(
            name='MessageMention',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mention_text', models.CharField(help_text='The actual mention text used', max_length=100)),
                ('position_start', models.PositiveIntegerField(help_text='Start position in message content')),
                ('position_end', models.PositiveIntegerField(help_text='End position in message content')),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_read', models.BooleanField(default=False)),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_mentions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='chat_messaging.message')),
            ],
            options={
                'verbose_name': 'Message Mention',
                'verbose_name_plural': 'Message Mentions',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠')], max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat_messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Reaction',
                'verbose_name_plural': 'Message Reactions',
            },
        ),
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='chat_messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Read Receipt',
                'verbose_name_plural': 'Message Read Receipts',
            },
        ),
        migrations.CreateModel(
            name='MessageTranslation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_language', models.CharField(help_text='Language code (e.g., en, es, fr)', max_length=10)),
                ('translated_content', models.TextField()),
                ('translation_service', models.CharField(default='google', max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('source_language', models.CharField(help_text='Detected source language', max_length=10)),
                ('is_auto_translation', models.BooleanField(default=True)),
                ('human_reviewed', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chat_messaging.message')),
            ],
            options={
                'verbose_name': 'Message Translation',
                'verbose_name_plural': 'Message Translations',
            },
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_typing', models.BooleanField(default=True)),
                ('last_typing_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='chat_conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typing Indicator',
                'verbose_name_plural': 'Typing Indicators',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_ffbe85_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__1b93b1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='chat_messag_message_f890fa_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['delivery_status'], name='chat_messag_deliver_db9a20_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_flagged'], name='chat_messag_is_flag_17fab9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread_id'], name='chat_messag_thread__996571_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_message_id'], name='chat_messag_client__bcb42c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_hash'], name='chat_messag_message_dd3403_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='chat_messag_message_a8b8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['file_type'], name='chat_messag_file_ty_bf93d8_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['file_hash'], name='chat_messag_file_ha_aa15f3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedeletion',
            index=models.Index(fields=['message'], name='chat_messag_message_317ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedeletion',
            index=models.Index(fields=['deleted_by'], name='chat_messag_deleted_9705dd_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedeletion',
            index=models.Index(fields=['deletion_reason'], name='chat_messag_deletio_d64e60_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemention',
            index=models.Index(fields=['message'], name='chat_messag_message_ac6356_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemention',
            index=models.Index(fields=['mentioned_user'], name='chat_messag_mention_c6d2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='chat_messag_message_e7e3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user'], name='chat_messag_user_id_d63612_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'reaction_type')},
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['message'], name='chat_messag_message_7200ee_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['user', 'read_at'], name='chat_messag_user_id_44fe06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagetranslation',
            index=models.Index(fields=['message'], name='chat_messag_message_8709ad_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetranslation',
            index=models.Index(fields=['target_language'], name='chat_messag_target__988b93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetranslation',
            unique_together={('message', 'target_language')},
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['conversation', 'is_typing'], name='chat_messag_convers_600dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['last_typing_at'], name='chat_messag_last_ty_529a15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingindicator',
            unique_together={('conversation', 'user')},
        ),
    ]
