# Generated by Django 5.1.11 on 2025-09-04 03:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_appuser_buyer_quote_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Payment identifier', primary_key=True, serialize=False)),
                ('payment_gateway', models.CharField(choices=[('PAYFAST', 'PayFast'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], help_text="'PAYFAST', 'STRIPE', 'PAYPAL'", max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Gateway transaction reference', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(help_text='Currency code', max_length=3)),
                ('payment_method', models.CharField(help_text='Payment method used', max_length=50)),
                ('gateway_response', models.JSONField(blank=True, help_text='Complete gateway response', null=True)),
                ('escrow_release_date', models.DateTimeField(blank=True, help_text='Scheduled payment release', null=True)),
                ('actual_release_date', models.DateTimeField(blank=True, help_text='Actual payment release', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], default='PENDING', help_text="'PENDING', 'AUTHORIZED', 'CAPTURED', 'RELEASED', 'REFUNDED'", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modified')),
                ('transaction_id', models.ForeignKey(help_text='Reference to Transactions.transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payment_tra_transac_2744e5_idx'), models.Index(fields=['payment_gateway'], name='payment_tra_payment_9bad68_idx'), models.Index(fields=['status'], name='payment_tra_status_3d273f_idx'), models.Index(fields=['escrow_release_date'], name='payment_tra_escrow__dac9db_idx')],
            },
        ),
    ]
