# Generated by Django 5.1.11 on 2025-08-08 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Transaction identifier', primary_key=True, serialize=False)),
                ('quote_id', models.UUIDField(help_text='Reference to Quotes.quote_id')),
                ('buyer_pin', models.CharField(help_text='6-digit buyer PIN', max_length=6)),
                ('seller_pin', models.CharField(help_text='6-digit seller PIN', max_length=6)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(help_text='Currency code', max_length=3)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Delivery status', max_length=20)),
                ('tracking_number', models.CharField(blank=True, help_text='Shipment tracking number', max_length=100, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, help_text='Expected delivery date', null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, help_text='Actual delivery date', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='ACTIVE', help_text='Transaction status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modified')),
                ('buyer_id', models.ForeignKey(help_text='Reference to Users.user_id', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to=settings.AUTH_USER_MODEL)),
                ('seller_id', models.ForeignKey(help_text='Reference to Users.user_id', on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['quote_id'], name='transaction_quote_i_b6ac9a_idx'), models.Index(fields=['buyer_id'], name='transaction_buyer_i_3275a3_idx'), models.Index(fields=['seller_id'], name='transaction_seller__bf8c21_idx'), models.Index(fields=['payment_status'], name='transaction_payment_9e5bb1_idx'), models.Index(fields=['delivery_status'], name='transaction_deliver_a29ec4_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx')],
            },
        ),
    ]
