# Generated by Django 5.1.11 on 2025-09-04 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(default='BUYER', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='buyer', max_length=150, unique=True)),
                ('email', models.EmailField(default='buyer@example.com', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='seller', max_length=150, unique=True)),
                ('email', models.EmailField(default='seller@example.com', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_quote_i_b00527_idx',
            old_name='transaction_quote_i_b6ac9a_idx',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer_id',
            field=models.ForeignKey(help_text='Reference to Users.user_id', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_transactions', to='transactions.buyer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quote_id',
            field=models.ForeignKey(help_text='Reference to Quotes.quote_id', on_delete=django.db.models.deletion.CASCADE, related_name='quote_transactions', to='transactions.quote'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller_id',
            field=models.ForeignKey(help_text='Reference to Users.user_id', on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to='transactions.seller'),
        ),
    ]
