# Generated by Django 5.0.14 on 2025-08-10 00:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_conversations', '0001_initial'),
        ('chat_messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoModerationSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_moderation_enabled', models.BooleanField(default=True)),
                ('confidence_threshold', models.DecimalField(decimal_places=4, default=0.7, help_text='Minimum confidence score for auto-actions', max_digits=5)),
                ('profanity_filter_enabled', models.BooleanField(default=True)),
                ('spam_detection_enabled', models.BooleanField(default=True)),
                ('pii_protection_enabled', models.BooleanField(default=True)),
                ('hate_speech_detection_enabled', models.BooleanField(default=True)),
                ('max_messages_per_minute', models.PositiveIntegerField(default=20)),
                ('max_identical_messages', models.PositiveIntegerField(default=3)),
                ('rate_limit_window_minutes', models.PositiveIntegerField(default=5)),
                ('auto_escalate_high_confidence', models.BooleanField(default=True)),
                ('escalation_confidence_threshold', models.DecimalField(decimal_places=4, default=0.9, max_digits=5)),
                ('require_human_review_for_bans', models.BooleanField(default=True)),
                ('auto_ban_repeat_offenders', models.BooleanField(default=True)),
                ('repeat_offender_threshold', models.PositiveIntegerField(default=3)),
                ('notify_moderators_for_escalations', models.BooleanField(default=True)),
                ('notify_users_of_actions', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto Moderation Settings',
                'verbose_name_plural': 'Auto Moderation Settings',
            },
        ),
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('profanity', 'Profanity Filter'), ('personal_info', 'Personal Information'), ('spam', 'Spam Detection'), ('offensive', 'Offensive Content'), ('scam', 'Scam/Fraud Detection'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence/Threats'), ('adult_content', 'Adult Content'), ('custom', 'Custom Rule')], max_length=20)),
                ('pattern', models.TextField(help_text='Regex pattern, keyword list, or ML model identifier')),
                ('action', models.CharField(choices=[('flag', 'Flag for Review'), ('block', 'Block Message'), ('warn', 'Warn User'), ('mask', 'Mask Content'), ('replace', 'Replace with Alternative'), ('escalate', 'Escalate to Human Review'), ('ban_user', 'Ban User')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_case_sensitive', models.BooleanField(default=False)),
                ('language_codes', models.JSONField(default=list, help_text='Languages this rule applies to')),
                ('replacement_text', models.TextField(blank=True, help_text='Text to replace matches with')),
                ('confidence_threshold', models.DecimalField(decimal_places=4, default=0.8, help_text='Minimum confidence for ML-based rules', max_digits=5)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('false_positive_count', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_moderation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Rule',
                'verbose_name_plural': 'Moderation Rules',
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('message', 'Message'), ('profile', 'User Profile'), ('file', 'File Upload'), ('conversation', 'Conversation')], max_length=20)),
                ('content_id', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('message_flagged', 'Message Flagged'), ('message_blocked', 'Message Blocked'), ('message_masked', 'Message Masked'), ('user_warned', 'User Warned'), ('user_banned', 'User Banned'), ('content_removed', 'Content Removed'), ('escalated', 'Escalated to Human'), ('false_positive', 'False Positive Reported')], max_length=30)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('reason', models.TextField(help_text='Reason for the action')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_automated', models.BooleanField(default=True)),
                ('original_content', models.TextField(help_text='Snapshot of original content')),
                ('modified_content', models.TextField(blank=True, help_text='Content after moderation')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_status', models.CharField(blank=True, choices=[('upheld', 'Action Upheld'), ('overturned', 'Action Overturned'), ('modified', 'Action Modified'), ('pending', 'Under Review')], max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
                ('rule_triggered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_moderation.moderationrule')),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
            },
        ),
        migrations.CreateModel(
            name='UserWarning',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warning_type', models.CharField(choices=[('content_violation', 'Content Policy Violation'), ('spam', 'Spam Behavior'), ('harassment', 'Harassment'), ('inappropriate_content', 'Inappropriate Content'), ('personal_info_sharing', 'Sharing Personal Information'), ('scam_attempt', 'Scam/Fraud Attempt'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this warning expires', null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL)),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_conversations.conversation')),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat_messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Warning',
                'verbose_name_plural': 'User Warnings',
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ban_type', models.CharField(choices=[('temporary', 'Temporary Ban'), ('permanent', 'Permanent Ban'), ('shadow', 'Shadow Ban')], max_length=20)),
                ('ban_scope', models.CharField(choices=[('global', 'Global (All chat features)'), ('messaging', 'Messaging only'), ('group_chat', 'Group chats only'), ('file_sharing', 'File sharing only')], default='global', max_length=20)),
                ('reason', models.TextField()),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for staff')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for permanent ban', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_reason', models.TextField(blank=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_bans', to=settings.AUTH_USER_MODEL)),
                ('related_actions', models.ManyToManyField(blank=True, to='chat_moderation.moderationaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
                ('related_warnings', models.ManyToManyField(blank=True, to='chat_moderation.userwarning')),
            ],
            options={
                'verbose_name': 'User Ban',
                'verbose_name_plural': 'User Bans',
            },
        ),
        migrations.AddIndex(
            model_name='moderationrule',
            index=models.Index(fields=['rule_type'], name='chat_modera_rule_ty_050f87_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationrule',
            index=models.Index(fields=['is_enabled'], name='chat_modera_is_enab_cd5a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationrule',
            index=models.Index(fields=['severity'], name='chat_modera_severit_1e079a_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['content_type', 'content_id'], name='chat_modera_content_d0f077_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_type'], name='chat_modera_action__245c55_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_user'], name='chat_modera_target__511ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['is_automated'], name='chat_modera_is_auto_555a25_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['created_at'], name='chat_modera_created_91b877_idx'),
        ),
        migrations.AddIndex(
            model_name='userwarning',
            index=models.Index(fields=['user'], name='chat_modera_user_id_aa9e79_idx'),
        ),
        migrations.AddIndex(
            model_name='userwarning',
            index=models.Index(fields=['warning_type'], name='chat_modera_warning_910b30_idx'),
        ),
        migrations.AddIndex(
            model_name='userwarning',
            index=models.Index(fields=['severity'], name='chat_modera_severit_e01110_idx'),
        ),
        migrations.AddIndex(
            model_name='userwarning',
            index=models.Index(fields=['is_acknowledged'], name='chat_modera_is_ackn_b3c748_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['user'], name='chat_modera_user_id_735c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['ban_type'], name='chat_modera_ban_typ_476c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['is_active'], name='chat_modera_is_acti_9f9811_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['expires_at'], name='chat_modera_expires_b424fa_idx'),
        ),
    ]
