# Generated by Django 5.0.14 on 2025-08-09 12:34

import django.core.validators
import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or emoji', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired'), ('draft', 'Draft')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission rate as percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('date', 'Date'), ('datetime', 'Date Time'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Phone'), ('color', 'Color'), ('file', 'File'), ('image', 'Image')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField(default=False)),
                ('show_in_listing', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('help_text', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('regex_pattern', models.CharField(blank=True, max_length=200)),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of choices for choice-based attributes')),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='categories.category')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategorySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('VEHICLE_SPARES', 'Vehicle Spares'), ('TYRES_RIMS', 'Tyres & Rims'), ('ELECTRONICS', 'Electronics')], help_text='Type identifier for category-specific specifications', max_length=20)),
                ('specification_schema', models.JSONField(help_text='JSON schema defining required fields for this category')),
                ('form_template', models.JSONField(blank=True, help_text='UI form template configuration', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category Specification',
                'verbose_name_plural': 'Category Specifications',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status', 'show_in_menu'], name='categories__status_9ec443_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'status'], name='categories__parent__578c02_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='categories__is_feat_283251_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryattribute',
            index=models.Index(fields=['category', 'is_required'], name='categories__categor_0949c3_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryattribute',
            index=models.Index(fields=['category', 'is_filterable'], name='categories__categor_4d7821_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together={('category', 'name')},
        ),
    ]
