# Generated by Django 5.1.11 on 2025-09-04 03:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_appuser_buyer_quote_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('return_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Return identifier', primary_key=True, serialize=False)),
                ('return_reason', models.CharField(help_text='Reason for return', max_length=100)),
                ('return_description', models.TextField(help_text='Detailed return description')),
                ('condition_photos', models.JSONField(help_text='Array of photo URLs')),
                ('return_shipping_address', models.JSONField(help_text='Return address details')),
                ('return_tracking_number', models.CharField(blank=True, help_text='Return shipment tracking', max_length=100, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Refund amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('admin_notes', models.TextField(blank=True, help_text='Administrative comments', null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='REQUESTED', help_text="'REQUESTED', 'APPROVED', 'REJECTED', 'COMPLETED'", max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Return request date')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Processing completion date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modified')),
                ('transaction_id', models.ForeignKey(help_text='Reference to Transactions.transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='product_ret_transac_ac5cb3_idx'), models.Index(fields=['status'], name='product_ret_status_f7d84a_idx'), models.Index(fields=['requested_at'], name='product_ret_request_d02ee0_idx')],
            },
        ),
    ]
