# Generated by Django 5.0.14 on 2025-08-10 02:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('vehicle_parts', 'Vehicle Parts'), ('electronics', 'Electronics'), ('custom_high_value', 'Custom/High-value Items'), ('general', 'General Items')], max_length=20)),
                ('hold_period_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('actual_release_date', models.DateTimeField(blank=True, null=True)),
                ('early_release_requested', models.BooleanField(default=False)),
                ('early_release_approved', models.BooleanField(default=False)),
                ('early_release_requested_at', models.DateTimeField(blank=True, null=True)),
                ('early_release_approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('early_released', 'Early Released'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='active', max_length=20)),
                ('release_reason', models.TextField(blank=True, help_text='Reason for early release or completion', null=True)),
                ('dispute_reason', models.TextField(blank=True, help_text='Reason for dispute if applicable', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('early_release_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_early_releases', to=settings.AUTH_USER_MODEL)),
                ('early_release_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_early_releases', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_period', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Escrow Period',
                'verbose_name_plural': 'Escrow Periods',
                'db_table': 'escrow_periods',
            },
        ),
        migrations.CreateModel(
            name='EscrowEarlyReleaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('supporting_documents', models.JSONField(default=list, help_text='List of supporting document URLs')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('buyer_approved', models.BooleanField(blank=True, help_text='Buyer approval for early release', null=True)),
                ('seller_approved', models.BooleanField(blank=True, help_text='Seller approval for early release', null=True)),
                ('admin_review_required', models.BooleanField(default=False)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_release_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_release_requests', to=settings.AUTH_USER_MODEL)),
                ('escrow_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_release_requests', to='escrow.escrowperiod')),
            ],
            options={
                'verbose_name': 'Escrow Early Release Request',
                'verbose_name_plural': 'Escrow Early Release Requests',
                'db_table': 'escrow_early_release_requests',
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('vehicle_parts', 'Vehicle Parts'), ('electronics', 'Electronics'), ('custom_high_value', 'Custom/High-value Items'), ('default', 'Default')], default='default', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('early_release_requested', models.BooleanField(default=False)),
                ('early_release_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='escrow_escr_status_0c88f9_idx'), models.Index(fields=['category'], name='escrow_escr_categor_42f558_idx'), models.Index(fields=['end_date'], name='escrow_escr_end_dat_d38120_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='escrowperiod',
            index=models.Index(fields=['transaction'], name='escrow_peri_transac_b009ae_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowperiod',
            index=models.Index(fields=['status'], name='escrow_peri_status_1f39ba_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowperiod',
            index=models.Index(fields=['end_date'], name='escrow_peri_end_dat_0e99ea_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowperiod',
            index=models.Index(fields=['early_release_requested'], name='escrow_peri_early_r_b50b04_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowearlyreleaserequest',
            index=models.Index(fields=['escrow_period'], name='escrow_earl_escrow__d59d60_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowearlyreleaserequest',
            index=models.Index(fields=['requested_by'], name='escrow_earl_request_623bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowearlyreleaserequest',
            index=models.Index(fields=['status'], name='escrow_earl_status_9b43b4_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowearlyreleaserequest',
            index=models.Index(fields=['created_at'], name='escrow_earl_created_c0b19f_idx'),
        ),
    ]
