apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bidr

resources:
- namespace.yaml
- secret.yaml
- configmap.yaml
- postgres.yaml
- bidr-app.yaml
- init-job.yaml
- hpa.yaml
- network-policy.yaml
- nginx-proxy.yaml

commonLabels:
  app.kubernetes.io/name: bidr
  app.kubernetes.io/part-of: bidr-platform
  app.kubernetes.io/managed-by: kustomize

replicas:
- name: bidr-app
  count: 2
