apiVersion: v1
kind: Namespace
metadata:
  name: bidr
  labels:
    name: bidr
    environment: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bidr-service-account
  namespace: bidr
  labels:
    app: bidr-services
    environment: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bidr
  name: bidr-service-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bidr-service-rolebinding
  namespace: bidr
subjects:
- kind: ServiceAccount
  name: bidr-service-account
  namespace: bidr
roleRef:
  kind: Role
  name: bidr-service-role
  apiGroup: rbac.authorization.k8s.io
