# Generated by Django 5.0.14 on 2025-08-02 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIScope',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Unique name for the API scope', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Description of what this scope allows')),
                ('resource', models.CharField(help_text="Resource this scope applies to (e.g., 'bids', 'users')", max_length=100)),
                ('permissions', models.JSONField(default=list, help_text="List of permissions (e.g., ['read', 'write', 'delete'])")),
                ('is_default', models.BooleanField(default=False, help_text='Whether this scope is included by default')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this scope requires special approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Scope',
                'verbose_name_plural': 'API Scopes',
                'db_table': 'api_scopes',
                'ordering': ['resource', 'name'],
                'indexes': [models.Index(fields=['name'], name='api_scopes_name_64aa98_idx'), models.Index(fields=['resource'], name='api_scopes_resourc_4f6113_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for the API key', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Description of the API key's purpose", null=True)),
                ('key_id', models.CharField(help_text='Public key identifier', max_length=32, unique=True)),
                ('key_hash', models.CharField(help_text='Hashed version of the secret key', max_length=128)),
                ('key_prefix', models.CharField(help_text='Visible prefix of the key for identification', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', help_text='Current status of the API key', max_length=20)),
                ('allowed_ips', models.JSONField(default=list, help_text='List of allowed IP addresses (empty = all allowed)')),
                ('allowed_origins', models.JSONField(default=list, help_text='List of allowed origins for CORS')),
                ('rate_limit_requests', models.IntegerField(default=1000, help_text='Number of requests allowed per period')),
                ('rate_limit_period', models.CharField(choices=[('minute', 'Per Minute'), ('hour', 'Per Hour'), ('day', 'Per Day'), ('month', 'Per Month')], default='hour', help_text='Rate limiting period', max_length=10)),
                ('daily_request_limit', models.IntegerField(blank=True, help_text='Maximum requests per day (null = unlimited)', null=True)),
                ('monthly_request_limit', models.IntegerField(blank=True, help_text='Maximum requests per month (null = unlimited)', null=True)),
                ('total_requests', models.BigIntegerField(default=0, help_text='Total number of requests made with this key')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this API key was used', null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last usage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the API key expires (null = never)', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the API key was revoked', null=True)),
                ('last_rotated_at', models.DateTimeField(blank=True, help_text='When the API key was last rotated', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
                ('scopes', models.ManyToManyField(blank=True, help_text='API scopes this key has access to', to='api_management.apiscope')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('minute', 'Per Minute'), ('hour', 'Per Hour'), ('day', 'Per Day'), ('month', 'Per Month')], help_text='Rate limiting period', max_length=10)),
                ('bucket_key', models.CharField(help_text='Unique key for this time bucket', max_length=100)),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests in this bucket')),
                ('first_request_at', models.DateTimeField(help_text='Timestamp of first request in bucket')),
                ('last_request_at', models.DateTimeField(help_text='Timestamp of last request in bucket')),
                ('expires_at', models.DateTimeField(help_text='When this bucket expires')),
                ('api_key', models.ForeignKey(help_text='API key this bucket belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit_buckets', to='api_management.apikey')),
            ],
            options={
                'verbose_name': 'Rate Limit Bucket',
                'verbose_name_plural': 'Rate Limit Buckets',
                'db_table': 'rate_limit_buckets',
                'ordering': ['-last_request_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageQuota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quota_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], help_text='Type of quota period', max_length=10)),
                ('period_start', models.DateTimeField(help_text='Start of the quota period')),
                ('period_end', models.DateTimeField(help_text='End of the quota period')),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests in this quota period')),
                ('quota_limit', models.IntegerField(help_text='Maximum requests allowed in this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(help_text='API key this quota belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to='api_management.apikey')),
            ],
            options={
                'verbose_name': 'API Key Usage Quota',
                'verbose_name_plural': 'API Key Usage Quotas',
                'db_table': 'api_key_usage_quotas',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['api_key', 'quota_type'], name='api_key_usa_api_key_d6068a_idx'), models.Index(fields=['period_end'], name='api_key_usa_period__9da30f_idx')],
                'unique_together': {('api_key', 'quota_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('endpoint', models.CharField(help_text='API endpoint accessed', max_length=500)),
                ('status_code', models.IntegerField(help_text='HTTP status code returned')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('origin', models.CharField(blank=True, help_text='Request origin', max_length=255, null=True)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('request_size', models.IntegerField(default=0, help_text='Request size in bytes')),
                ('response_size', models.IntegerField(default=0, help_text='Response size in bytes')),
                ('query_params', models.JSONField(default=dict, help_text='Query parameters (sanitized)')),
                ('request_headers', models.JSONField(default=dict, help_text='Request headers (sanitized)')),
                ('error_details', models.JSONField(default=dict, help_text='Error details if request failed')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the request was made')),
                ('api_key', models.ForeignKey(help_text='API key used for this request', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api_management.apikey')),
            ],
            options={
                'verbose_name': 'API Request',
                'verbose_name_plural': 'API Requests',
                'db_table': 'api_requests',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='api_request_api_key_cb0f34_idx'), models.Index(fields=['endpoint', 'timestamp'], name='api_request_endpoin_2c1c1e_idx'), models.Index(fields=['status_code'], name='api_request_status__f5b5a7_idx'), models.Index(fields=['ip_address'], name='api_request_ip_addr_2a301e_idx'), models.Index(fields=['timestamp'], name='api_request_timesta_0d07d6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_id'], name='api_keys_key_id_a77510_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', 'status'], name='api_keys_user_id_c5312c_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['status'], name='api_keys_status_753779_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['last_used_at'], name='api_keys_last_us_fbf652_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitbucket',
            index=models.Index(fields=['api_key', 'period'], name='rate_limit__api_key_995642_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitbucket',
            index=models.Index(fields=['expires_at'], name='rate_limit__expires_b25e16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimitbucket',
            unique_together={('api_key', 'period', 'bucket_key')},
        ),
    ]
