# Generated by Django 5.0.14 on 2025-08-10 03:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('webhook', 'Webhook'), ('slack', 'Slack'), ('discord', 'Discord'), ('teams', 'Microsoft Teams'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Channel-specific configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit', models.PositiveIntegerField(default=0, help_text='Messages per minute (0 = no limit)')),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, help_text='External provider name', max_length=50)),
                ('api_endpoint', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['channel_type'], name='delivery_ch_channel_f4b621_idx'), models.Index(fields=['is_active'], name='delivery_ch_is_acti_7e87c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_id', models.UUIDField(help_text='Reference to notification in system_notifications')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='ID from external service', max_length=255)),
                ('external_status', models.CharField(blank=True, max_length=50)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_channels.notificationchannel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_id'], name='delivery_ch_notific_ac6383_idx'), models.Index(fields=['status'], name='delivery_ch_status_78c670_idx'), models.Index(fields=['channel', '-created_at'], name='delivery_ch_channel_e50af4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_window', models.CharField(choices=[('minute', 'Per Minute'), ('hour', 'Per Hour'), ('day', 'Per Day'), ('month', 'Per Month')], max_length=20)),
                ('max_requests', models.PositiveIntegerField()),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='delivery_channels.notificationchannel')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'time_window'], name='delivery_ch_channel_058bcf_idx')],
                'unique_together': {('channel', 'time_window')},
            },
        ),
        migrations.CreateModel(
            name='ChannelCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=100)),
                ('encrypted_value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='delivery_channels.notificationchannel')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'key_name'], name='delivery_ch_channel_7eeeba_idx')],
                'unique_together': {('channel', 'key_name')},
            },
        ),
    ]
