# Generated by Django 5.0.14 on 2025-08-10 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('auto_escalate_hours', models.PositiveIntegerField(default=72)),
                ('requires_evidence', models.BooleanField(default=True)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_disputes', models.PositiveIntegerField(default=0)),
                ('new_disputes', models.PositiveIntegerField(default=0)),
                ('resolved_disputes', models.PositiveIntegerField(default=0)),
                ('escalated_disputes', models.PositiveIntegerField(default=0)),
                ('full_refunds', models.PositiveIntegerField(default=0)),
                ('partial_refunds', models.PositiveIntegerField(default=0)),
                ('replacements', models.PositiveIntegerField(default=0)),
                ('no_actions', models.PositiveIntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('return_rejected', 'Return Rejected'), ('refund_denied', 'Refund Denied'), ('item_not_received', 'Item Not Received'), ('item_damaged', 'Item Damaged'), ('not_as_described', 'Not as Described'), ('payment_issue', 'Payment Issue'), ('shipping_issue', 'Shipping Issue'), ('communication_issue', 'Communication Issue'), ('other', 'Other')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('desired_resolution', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('awaiting_response', 'Awaiting Response'), ('escalated', 'Escalated to Admin'), ('mediation', 'In Mediation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('disputed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_escalate_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('replacement', 'Replacement'), ('store_credit', 'Store Credit'), ('no_action', 'No Action Required'), ('other', 'Other')], max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_filed', to=settings.AUTH_USER_MODEL)),
                ('mediator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_mediated', to=settings.AUTH_USER_MODEL)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_received', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='returns.returnrequest')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transactionreference')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('screenshot', 'Screenshot'), ('receipt', 'Receipt'), ('communication', 'Communication Log'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='disputes/evidence/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='disputes.dispute')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('is_resolution_offer', models.BooleanField(default=False)),
                ('read_by_complainant', models.BooleanField(default=False)),
                ('read_by_respondent', models.BooleanField(default=False)),
                ('read_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResolutionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('replacement', 'Replacement'), ('store_credit', 'Store Credit'), ('discount', 'Discount on Future Purchase'), ('other', 'Other')], max_length=20)),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=15)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_offers', to='disputes.dispute')),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='disputes.dispute')),
            ],
            options={
                'verbose_name_plural': 'Dispute status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('chat', 'Chat Session'), ('video', 'Video Call'), ('phone', 'Phone Call'), ('email', 'Email Exchange')], default='chat', max_length=15)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('complainant_attended', models.BooleanField(default=False)),
                ('respondent_attended', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('agreement', 'Agreement Reached'), ('partial', 'Partial Agreement'), ('no_agreement', 'No Agreement'), ('escalated', 'Escalated to Admin'), ('cancelled', 'Cancelled')], max_length=15)),
                ('mediator_notes', models.TextField(blank=True)),
                ('agreement_terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediation', to='disputes.dispute')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
