# Generated by Django 5.0.14 on 2025-08-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_guard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadeletionrequest',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='datamaskingprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='piidetectionresult',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='piidetectionrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='privacyauditlog',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='privacyconsent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
    ]
