# Generated by Django 5.0.14 on 2025-08-10 00:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_conversations', '0001_initial'),
        ('chat_messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('icon_url', models.URLField(blank=True)),
                ('action_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Context used to render template')),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('device_token', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_service', to=settings.AUTH_USER_MODEL)),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_service', to='chat_conversations.conversation')),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_service', to='chat_messaging.message')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('do_not_disturb', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_start_time', models.TimeField(blank=True, null=True)),
                ('quiet_end_time', models.TimeField(blank=True, null=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('mention_notifications', models.BooleanField(default=True)),
                ('invitation_notifications', models.BooleanField(default=True)),
                ('reaction_notifications', models.BooleanField(default=True)),
                ('file_share_notifications', models.BooleanField(default=True)),
                ('moderation_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('notification_preview', models.BooleanField(default=True, help_text='Show message preview in notifications_service')),
                ('group_notifications', models.BooleanField(default=True, help_text='Group similar notifications_service')),
                ('sound_enabled', models.BooleanField(default=True)),
                ('vibration_enabled', models.BooleanField(default=True)),
                ('max_notifications_per_hour', models.PositiveIntegerField(default=50)),
                ('batch_delay_minutes', models.PositiveIntegerField(default=5, help_text='Delay for batching notifications_service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('template_type', models.CharField(choices=[('message_received', 'New Message Received'), ('mention_received', 'User Mentioned'), ('conversation_invite', 'Conversation Invitation'), ('message_reaction', 'Message Reaction'), ('typing_indicator', 'User Typing'), ('file_shared', 'File Shared'), ('conversation_archived', 'Conversation Archived'), ('moderation_warning', 'Moderation Warning'), ('user_banned', 'User Banned'), ('translation_ready', 'Translation Ready'), ('system_announcement', 'System Announcement'), ('custom', 'Custom Notification')], max_length=30)),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('title_template', models.CharField(help_text='Title with variables like {{user_name}}', max_length=200)),
                ('body_template', models.TextField(help_text='Body content with variables')),
                ('icon_url', models.URLField(blank=True, help_text='Icon URL for push notifications_service')),
                ('action_url', models.URLField(blank=True, help_text='URL to open when clicked')),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('delay_seconds', models.PositiveIntegerField(default=0, help_text='Delay before sending')),
                ('batch_notifications', models.BooleanField(default=False, help_text='Batch similar notifications_service')),
                ('variables', models.JSONField(default=list, help_text='List of available template variables')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('item_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notifications_service', models.ManyToManyField(related_name='batches', to='chat_notifications.notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_batches', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification Batch',
                'verbose_name_plural': 'Notification Batches',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_service', to='chat_notifications.notificationtemplate'),
        ),
        migrations.CreateModel(
            name='NotificationDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web Browser')], max_length=20)),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('os_version', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_notifications_sent', models.PositiveIntegerField(default=0)),
                ('total_notifications_delivered', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Device',
                'verbose_name_plural': 'Notification Devices',
                'indexes': [models.Index(fields=['user'], name='chat_notifi_user_id_16902a_idx'), models.Index(fields=['device_type'], name='chat_notifi_device__a6ddcd_idx'), models.Index(fields=['is_active'], name='chat_notifi_is_acti_b4de92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['template_type'], name='chat_notifi_templat_75c7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['channel'], name='chat_notifi_channel_9890b0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['is_enabled'], name='chat_notifi_is_enab_1a74b9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['recipient', 'status'], name='chat_notifi_recipie_de06ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['sent_at'], name='chat_notifi_sent_at_e3c283_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='chat_notifi_recipie_079c78_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='chat_notifi_status_5d5d92_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_at'], name='chat_notifi_schedul_c74e91_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='chat_notifi_priorit_1b6902_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='chat_notifi_expires_a6aea8_idx'),
        ),
    ]
