# Generated by Django 5.0.14 on 2025-08-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
    ]
