# Generated by Django 5.1.11 on 2025-09-04 03:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_appuser_buyer_quote_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowPeriod',
            fields=[
                ('escrow_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Escrow period identifier', primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('VEHICLE_SPARES', 'Vehicle Spares'), ('TYRES_RIMS', 'Tyres & Rims'), ('OTHER', 'Other')], help_text='Product category determining hold period', max_length=20)),
                ('hold_period_days', models.IntegerField(help_text='Days to hold payment')),
                ('start_date', models.DateTimeField(help_text='Escrow period start')),
                ('end_date', models.DateTimeField(help_text='Scheduled release date')),
                ('early_release_requested', models.BooleanField(default=False, help_text='Early release flag')),
                ('early_release_approved', models.BooleanField(default=False, help_text='Admin approval for early release')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('DISPUTED', 'Disputed')], default='ACTIVE', help_text='Escrow period status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modified')),
                ('transaction_id', models.ForeignKey(help_text='Reference to Transactions.transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='escrow_periods', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='escrow_peri_transac_8440b1_idx'), models.Index(fields=['category'], name='escrow_peri_categor_f37c41_idx'), models.Index(fields=['status'], name='escrow_peri_status_54e9de_idx'), models.Index(fields=['end_date'], name='escrow_peri_end_dat_21bc94_idx')],
            },
        ),
    ]
