# Generated by Django 5.0.14 on 2025-08-10 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='User ID from external service', unique=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('type_preferences', models.JSONField(blank=True, default=dict)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('digest_frequency', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='never', max_length=10)),
                ('last_digest_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='system_noti_user_id_ef1fba_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('payment_pending', 'Payment Pending'), ('refund_processed', 'Refund Processed'), ('escrow_released', 'Escrow Released'), ('review_received', 'Review Received'), ('review_response', 'Review Response'), ('review_flagged', 'Review Flagged'), ('return_request_received', 'Return Request Received'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('return_shipped', 'Return Shipped'), ('return_received', 'Return Received'), ('return_completed', 'Return Completed'), ('dispute_created', 'Dispute Created'), ('dispute_message', 'Dispute Message'), ('dispute_escalated', 'Dispute Escalated'), ('dispute_resolved', 'Dispute Resolved'), ('resolution_offer', 'Resolution Offer'), ('mediation_scheduled', 'Mediation Scheduled'), ('system_maintenance', 'System Maintenance'), ('policy_update', 'Policy Update'), ('account_update', 'Account Update'), ('security_alert', 'Security Alert'), ('new_message', 'New Message'), ('message_read', 'Message Read'), ('chat_archived', 'Chat Archived'), ('login_success', 'Login Successful'), ('login_failed', 'Login Failed'), ('password_changed', 'Password Changed'), ('account_locked', 'Account Locked'), ('custom', 'Custom Notification')], max_length=50)),
                ('subject_template', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('html_template', models.TextField(blank=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=True)),
                ('send_in_app', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['notification_type'], name='system_noti_notific_5168e7_idx'), models.Index(fields=['is_active'], name='system_noti_is_acti_4f9d3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField(help_text='User ID from external service')),
                ('notification_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('in_app_sent', models.BooleanField(default=False)),
                ('email_status', models.CharField(blank=True, max_length=20)),
                ('sms_status', models.CharField(blank=True, max_length=20)),
                ('push_status', models.CharField(blank=True, max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('source_service', models.CharField(blank=True, choices=[('payment_service', 'Payment Service'), ('resolution_service', 'Resolution Service'), ('chat_service', 'Chat Service'), ('auth_service', 'Authentication Service'), ('product_service', 'Product Service'), ('notification_service', 'Notification Service')], max_length=50)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField(default=5)),
                ('scheduled_for', models.DateTimeField()),
                ('is_processing', models.BooleanField(default=False)),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='system_notifications.notification')),
            ],
            options={
                'ordering': ['priority', 'scheduled_for'],
                'indexes': [models.Index(fields=['priority', 'scheduled_for'], name='system_noti_priorit_e59de0_idx'), models.Index(fields=['is_processing'], name='system_noti_is_proc_6bae0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(max_length=50)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_data', models.JSONField(default=dict)),
                ('created_by_id', models.UUIDField(help_text='Admin/System user ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='system_noti_status_ce3eb7_idx'), models.Index(fields=['notification_type'], name='system_noti_notific_9e6d7c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_id', '-created_at'], name='system_noti_recipie_f6d389_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='system_noti_notific_a49943_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='system_noti_is_read_5b20e6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='system_noti_priorit_d1f35d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['source_service'], name='system_noti_source__3322ce_idx'),
        ),
    ]
