# Generated by Django 5.0.14 on 2025-08-02 02:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='alternative_phone',
            field=models.CharField(blank=True, help_text='Encrypted alternative phone', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='currency_preference',
            field=models.CharField(default='USD', help_text='ISO currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_of_birth',
            field=models.CharField(blank=True, help_text='Encrypted date of birth', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='preferred_language',
            field=models.CharField(default='en', help_text='Language code (e.g., en, es, fr)', max_length=10),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('verified', 'Verified')], default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='show_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_timezone',
            field=models.CharField(default='UTC', help_text="User's timezone", max_length=50),
        ),
        migrations.AddField(
            model_name='appuser',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('is_visible', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_id', models.UUIDField(blank=True, help_text='Optional business ID for business addresses', null=True)),
                ('address_line_1', models.CharField(help_text='Encrypted address line 1', max_length=500)),
                ('address_line_2', models.CharField(blank=True, help_text='Encrypted address line 2', max_length=500, null=True)),
                ('city', models.CharField(help_text='Encrypted city', max_length=255)),
                ('state_province', models.CharField(help_text='Encrypted state/province', max_length=255)),
                ('postal_code', models.CharField(help_text='Encrypted postal code', max_length=50)),
                ('country', models.CharField(help_text='Encrypted country', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('business', 'Business'), ('shipping', 'Shipping'), ('billing', 'Billing')], default='home', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary address for the user?')),
                ('address_name', models.CharField(blank=True, help_text="Optional name for the address (e.g., 'Home', 'Office')", max_length=100, null=True)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Special delivery instructions', max_length=500, null=True)),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'db_table': 'user_address',
                'indexes': [models.Index(fields=['user', 'address_type'], name='user_addres_user_id_568ba8_idx'), models.Index(fields=['user', 'is_primary'], name='user_addres_user_id_6a71e7_idx'), models.Index(fields=['is_primary', 'is_deleted'], name='user_addres_is_prim_68d0d2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('user', 'address_type'), name='unique_primary_address_per_type'),
        ),
    ]
