# Generated by Django 5.0.14 on 2025-08-28 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPortalConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='SMS Portal', max_length=100, unique=True)),
                ('api_url', models.URLField(default='https://rest.smsportal.com/v1')),
                ('api_key', models.CharField(help_text='SMS Portal API Key', max_length=255)),
                ('api_secret', models.CharField(help_text='SMS Portal API Secret', max_length=255)),
                ('default_sender_id', models.CharField(help_text='Default sender ID/name', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Portal Configuration',
                'verbose_name_plural': 'SMS Portal Configurations',
                'db_table': 'sms_portal_config',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(help_text='SMS template with placeholders like {name}, {code}')),
                ('message_type', models.CharField(choices=[('otp', 'OTP Verification'), ('notification', 'General Notification'), ('alert', 'Alert Message'), ('marketing', 'Marketing Message'), ('system', 'System Message')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sender_id', models.CharField(blank=True, help_text='Override default sender ID', max_length=20)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
                'db_table': 'sms_portal_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('message_content', models.TextField(help_text='SMS message content')),
                ('sender_id', models.CharField(help_text='Sender ID used', max_length=20)),
                ('external_message_id', models.CharField(blank=True, help_text='SMS Portal message ID', max_length=100)),
                ('external_status', models.CharField(blank=True, help_text='Status from SMS Portal', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('rejected', 'Rejected')], default='queued', max_length=20)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('credits_used', models.PositiveIntegerField(default=1)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('notification_id', models.UUIDField(blank=True, help_text='Related notification ID', null=True)),
                ('message_type', models.CharField(choices=[('otp', 'OTP Verification'), ('notification', 'General Notification'), ('alert', 'Alert Message'), ('marketing', 'Marketing Message'), ('system', 'System Message')], default='notification', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'db_table': 'sms_portal_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_phone'], name='sms_portal__recipie_ccdd7f_idx'), models.Index(fields=['status'], name='sms_portal__status_7182d0_idx'), models.Index(fields=['external_message_id'], name='sms_portal__externa_e56029_idx'), models.Index(fields=['message_type'], name='sms_portal__message_cd5359_idx'), models.Index(fields=['-created_at'], name='sms_portal__created_695ead_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSUsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date for statistics')),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_delivered', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('total_bounced', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_credits_used', models.PositiveIntegerField(default=0)),
                ('otp_count', models.PositiveIntegerField(default=0)),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('alert_count', models.PositiveIntegerField(default=0)),
                ('marketing_count', models.PositiveIntegerField(default=0)),
                ('system_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Usage Statistics',
                'verbose_name_plural': 'SMS Usage Statistics',
                'db_table': 'sms_portal_usage_stats',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
