# Generated by Django 5.0.14 on 2025-08-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebackup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='fileprocessingjob',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='filethumbnail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='fileversion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
    ]
