apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../

patchesStrategicMerge:
- configmap-patch.yaml

replicas:
- name: bidr-app
  count: 1

images:
- name: bidrcontainerregistry.azurecr.io/bidr-app
  newTag: latest

commonLabels:
  environment: development
