# Generated by Django 5.0.14 on 2025-08-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automoderationsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='moderationrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='userwarning',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
    ]
