# Generated by Django 5.0.14 on 2025-09-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_ticket_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='seller_id',
            field=models.CharField(blank=True, help_text='External seller ID', max_length=100, null=True),
        ),
    ]
