# Generated by Django 5.0.14 on 2025-08-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='conversationbookmark',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='conversationinvite',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='conversationtag',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='conversationtagassignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
    ]
