# Generated by Django 5.0.14 on 2025-09-07 05:49

import django.core.validators
import django.db.models.deletion
import quotes.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Quote identifier', primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total quote amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(help_text='Currency code', max_length=3)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Delivery charges', max_digits=10, null=True)),
                ('installation_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Installation charges', max_digits=10, null=True)),
                ('estimated_delivery_days', models.IntegerField(blank=True, help_text='Delivery timeframe', null=True)),
                ('terms_conditions', models.TextField(blank=True, help_text='Quote terms', null=True)),
                ('seller_notes', models.TextField(blank=True, help_text='Additional seller comments', null=True)),
                ('warranty_info', models.JSONField(blank=True, help_text='Warranty details', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', help_text='Quote status', max_length=20)),
                ('valid_until', models.DateTimeField(default=quotes.models.get_default_expiry, help_text='Quote expiration')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modified')),
                ('request_id', models.ForeignKey(help_text='Reference to Product_Requests.request_id', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='product_requests.productrequest')),
                ('seller_id', models.ForeignKey(help_text='Reference to Users.user_id', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quotes/attachments/')),
                ('filename', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.quote')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quotes', models.IntegerField(default=0)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('highest_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comparison_data', models.JSONField(default=dict, help_text='Detailed comparison analysis')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('best_delivery_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_delivery_comparisons', to='quotes.quote')),
                ('best_price_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_price_comparisons', to='quotes.quote')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_comparison', to='product_requests.productrequest')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('clarification', 'Clarification'), ('negotiation', 'Negotiation'), ('revision', 'Revision Request'), ('acceptance', 'Acceptance'), ('rejection', 'Rejection'), ('system', 'System Message')], default='clarification', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal messages not visible to other party')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='quotes.quote')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_quote_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['request_id'], name='quotes_quot_request_ee3464_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['seller_id'], name='quotes_quot_seller__6fd224_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='quotes_quot_status_bc6cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='quotecomparison',
            index=models.Index(fields=['request'], name='quotes_quot_request_b50574_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['quote', 'sort_order'], name='quotes_quot_quote_i_474c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='quotemessage',
            index=models.Index(fields=['quote', 'created_at'], name='quotes_quot_quote_i_7a8977_idx'),
        ),
        migrations.AddIndex(
            model_name='quotemessage',
            index=models.Index(fields=['sender'], name='quotes_quot_sender__c13da6_idx'),
        ),
    ]
