# Generated by Django 5.0.14 on 2025-08-10 03:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.URLField()),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveIntegerField()),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('processing_time_ms', models.PositiveIntegerField(help_text='Processing time in milliseconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method', 'endpoint'], name='notificatio_method_c084a8_idx'), models.Index(fields=['response_status'], name='notificatio_respons_662eda_idx'), models.Index(fields=['-created_at'], name='notificatio_created_a020aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='User who performed the action')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('permission_change', 'Permission Change'), ('bulk_action', 'Bulk Action')], max_length=100)),
                ('resource_type', models.CharField(help_text='Type of resource affected', max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the specific resource', max_length=100)),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Before/after values for updates')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='notificatio_user_id_8fe34d_idx'), models.Index(fields=['action'], name='notificatio_action_2d0931_idx'), models.Index(fields=['resource_type'], name='notificatio_resourc_2173fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(help_text='Exception class name', max_length=100)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('component', models.CharField(max_length=50)),
                ('function_name', models.CharField(blank=True, max_length=100)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('notification_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_url', models.URLField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['error_type'], name='notificatio_error_t_93fd7a_idx'), models.Index(fields=['component'], name='notificatio_compone_626ea4_idx'), models.Index(fields=['is_resolved', '-created_at'], name='notificatio_is_reso_3a739c_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_id', models.UUIDField(help_text='Reference to notification in system_notifications')),
                ('channel_type', models.CharField(max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('rejected', 'Rejected'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='ID from external service', max_length=255)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_id'], name='notificatio_notific_442c4a_idx'), models.Index(fields=['status'], name='notificatio_status_9fee2f_idx'), models.Index(fields=['channel_type', '-created_at'], name='notificatio_channel_7dad6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('component', models.CharField(help_text='System component that generated the log', max_length=50)),
                ('action', models.CharField(help_text='Action being performed', max_length=100)),
                ('message', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('user_id', models.UUIDField(blank=True, help_text='User ID if action was user-initiated', null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', '-created_at'], name='notificatio_level_1fdd7e_idx'), models.Index(fields=['component'], name='notificatio_compone_964697_idx'), models.Index(fields=['user_id'], name='notificatio_user_id_fb00ec_idx')],
            },
        ),
    ]
