# Generated by Django 5.0.14 on 2025-08-02 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('api', 'API Client'), ('unknown', 'Unknown')], default='unknown', help_text='Type of device used', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text='Human-readable device name', max_length=255, null=True)),
                ('browser', models.CharField(blank=True, help_text='Browser used for the session', max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, help_text='Browser version', max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, help_text='Operating system', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the session')),
                ('user_agent', models.TextField(blank=True, help_text='Full user agent string', null=True)),
                ('country', models.CharField(blank=True, help_text='Country from IP geolocation', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='City from IP geolocation', max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('suspended', 'Suspended')], default='active', help_text='Current status of the session', max_length=20)),
                ('is_trusted', models.BooleanField(default=False, help_text='Whether this device/location is trusted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('expires_at', models.DateTimeField(help_text='When the session expires')),
                ('terminated_at', models.DateTimeField(blank=True, help_text='When the session was terminated', null=True)),
                ('security_score', models.IntegerField(default=50, help_text='Security score for this session (0-100)')),
                ('risk_factors', models.JSONField(default=list, help_text='List of identified risk factors')),
                ('user', models.ForeignKey(help_text='User associated with this session', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='SessionSecurityEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('suspicious_location', 'Suspicious Location'), ('multiple_sessions', 'Multiple Active Sessions'), ('unusual_activity', 'Unusual Activity Pattern'), ('brute_force', 'Brute Force Attempt'), ('session_hijack', 'Potential Session Hijacking'), ('untrusted_device', 'Untrusted Device Access')], help_text='Type of security event', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the event', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the security event')),
                ('event_data', models.JSONField(default=dict, help_text='Additional data related to the security event')),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score assigned to this event (0-100)')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the security event has been resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the event was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the event was resolved', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When the security event was detected')),
                ('session', models.ForeignKey(help_text='Session where the security event occurred', on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='user_sessions.usersession')),
            ],
            options={
                'verbose_name': 'Session Security Event',
                'verbose_name_plural': 'Session Security Events',
                'db_table': 'session_security_events',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Type of action performed', max_length=100)),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint or page accessed', max_length=500, null=True)),
                ('method', models.CharField(blank=True, help_text='HTTP method used', max_length=10, null=True)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code', null=True)),
                ('request_data', models.JSONField(default=dict, help_text='Request data (sanitized)')),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the activity occurred')),
                ('session', models.ForeignKey(help_text='Session this activity belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='user_sessions.usersession')),
            ],
            options={
                'verbose_name': 'Session Activity',
                'verbose_name_plural': 'Session Activities',
                'db_table': 'session_activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255)),
                ('device_name', models.CharField(help_text='Human-readable device name', max_length=255)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('api', 'API Client'), ('unknown', 'Unknown')], help_text='Type of device', max_length=20)),
                ('device_fingerprint', models.TextField(help_text='Device fingerprint hash')),
                ('trusted_at', models.DateTimeField(auto_now_add=True, help_text='When the device was marked as trusted')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Last time this device was used')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the trust expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the trust is currently active')),
                ('user', models.ForeignKey(help_text='User who owns this trusted device', on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'db_table': 'trusted_devices',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='trusted_dev_user_id_02eb40_idx'), models.Index(fields=['device_id'], name='trusted_dev_device__232a37_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'status'], name='user_sessio_user_id_b0c39f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['ip_address'], name='user_sessio_ip_addr_0626e4_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['device_id'], name='user_sessio_device__4ac8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='user_sessio_last_ac_7cb421_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionsecurityevent',
            index=models.Index(fields=['session', 'event_type'], name='session_sec_session_f4b581_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionsecurityevent',
            index=models.Index(fields=['severity', 'is_resolved'], name='session_sec_severit_27b18e_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionsecurityevent',
            index=models.Index(fields=['detected_at'], name='session_sec_detecte_34342a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['session', 'timestamp'], name='session_act_session_5187f0_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['action'], name='session_act_action_88e7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionactivity',
            index=models.Index(fields=['endpoint'], name='session_act_endpoin_538aca_idx'),
        ),
    ]
