# Generated by Django 5.0.14 on 2025-08-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='messagedeletion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='messagemention',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='messagetranslation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='typingindicator',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag'),
        ),
    ]
