# Generated by Django 5.0.14 on 2025-09-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messaging', '0003_allow_null_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Display name of the message sender', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_role',
            field=models.CharField(blank=True, default='user', help_text='Role of the message sender (user, admin, moderator, etc.)', max_length=50),
        ),
    ]
