# Generated by Django 5.0.14 on 2025-08-09 13:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('product_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryanalytics',
            name='active_products',
        ),
        migrations.RemoveField(
            model_name='categoryanalytics',
            name='new_products',
        ),
        migrations.RemoveField(
            model_name='categoryanalytics',
            name='total_products',
        ),
        migrations.AddField(
            model_name='categoryanalytics',
            name='active_requests',
            field=models.IntegerField(default=0, help_text='Number of active product requests'),
        ),
        migrations.AddField(
            model_name='categoryanalytics',
            name='closed_requests',
            field=models.IntegerField(default=0, help_text='Number of closed requests in this period'),
        ),
        migrations.AddField(
            model_name='categoryanalytics',
            name='new_requests',
            field=models.IntegerField(default=0, help_text='New product requests added in this period'),
        ),
        migrations.AddField(
            model_name='categoryanalytics',
            name='total_quote_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoryanalytics',
            name='total_requests',
            field=models.IntegerField(default=0, help_text='Total number of product requests in category'),
        ),
        migrations.CreateModel(
            name='ProductRequestAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(help_text='Date this analytics record represents')),
                ('timeframe', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('unique_views', models.IntegerField(default=0, help_text='Number of unique views')),
                ('search_appearances', models.IntegerField(default=0, help_text='Times request appeared in search results')),
                ('search_clicks', models.IntegerField(default=0, help_text='Times request was clicked from search results')),
                ('quote_responses', models.IntegerField(default=0, help_text='Number of quote responses received')),
                ('messages_sent', models.IntegerField(default=0, help_text='Number of messages sent to requestor')),
                ('watchlist_additions', models.IntegerField(default=0, help_text='Number of times added to watchlist')),
                ('average_response_time', models.DurationField(blank=True, help_text='Average response time for quotes', null=True)),
                ('supplier_interest_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Score based on supplier engagement (0-100)', max_digits=5)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='product_requests.productrequest')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['request', 'date'], name='analytics_p_request_87f8c4_idx'), models.Index(fields=['date', 'timeframe'], name='analytics_p_date_57d045_idx'), models.Index(fields=['supplier_interest_score', 'date'], name='analytics_p_supplie_c22fbf_idx')],
                'unique_together': {('request', 'date', 'timeframe')},
            },
        ),
    ]
