# Generated by Django 5.0.14 on 2025-08-10 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('record_count', models.PositiveIntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField()),
                ('compression_format', models.CharField(default='gzip', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_type', models.CharField(choices=[('response_time', 'Response Time'), ('database_query', 'Database Query'), ('cache_hit_rate', 'Cache Hit Rate'), ('memory_usage', 'Memory Usage'), ('cpu_usage', 'CPU Usage'), ('disk_usage', 'Disk Usage'), ('network_io', 'Network I/O'), ('custom', 'Custom Metric')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('query_type', models.CharField(blank=True, max_length=50)),
                ('additional_context', models.JSONField(blank=True, default=dict)),
                ('threshold_warning', models.FloatField(blank=True, null=True)),
                ('threshold_critical', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['metric_name', '-created_at'], name='logs_perfor_metric__836dec_idx'), models.Index(fields=['metric_type', '-created_at'], name='logs_perfor_metric__ab9ed7_idx'), models.Index(fields=['endpoint'], name='logs_perfor_endpoin_a90722_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('logger_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=100)),
                ('function', models.CharField(blank=True, max_length=100)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=100)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', '-created_at'], name='logs_system_level_c7c9de_idx'), models.Index(fields=['logger_name'], name='logs_system_logger__b7e6c9_idx'), models.Index(fields=['created_at'], name='logs_system_created_6d6f8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('authentication', 'Authentication'), ('review', 'Review Activity'), ('return', 'Return Activity'), ('dispute', 'Dispute Activity'), ('notification', 'Notification Activity'), ('admin', 'Admin Activity'), ('system', 'System Activity'), ('api', 'API Activity'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='logs_activi_user_id_824f53_idx'), models.Index(fields=['category', '-created_at'], name='logs_activi_categor_03d0bd_idx'), models.Index(fields=['action'], name='logs_activi_action_8a8766_idx'), models.Index(fields=['success'], name='logs_activi_success_9ac7d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.TextField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True)),
                ('request_body_size', models.PositiveIntegerField(default=0)),
                ('status_code', models.PositiveIntegerField()),
                ('response_body', models.TextField(blank=True)),
                ('response_body_size', models.PositiveIntegerField(default=0)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('processing_time', models.FloatField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=100)),
                ('auth_method', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('exception_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method', 'path'], name='logs_apireq_method_abe2bc_idx'), models.Index(fields=['status_code'], name='logs_apireq_status__9de2b2_idx'), models.Index(fields=['user', '-created_at'], name='logs_apireq_user_id_8254d6_idx'), models.Index(fields=['-created_at'], name='logs_apireq_created_162151_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('field_changes', models.JSONField(blank=True, default=dict)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='logs_datach_content_5f8711_idx'), models.Index(fields=['user', '-created_at'], name='logs_datach_user_id_b1dc25_idx'), models.Index(fields=['action', '-created_at'], name='logs_datach_action_d016b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('module', models.CharField(blank=True, max_length=100)),
                ('function', models.CharField(blank=True, max_length=100)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['error_type', '-created_at'], name='logs_errorl_error_t_9e68f3_idx'), models.Index(fields=['is_resolved'], name='logs_errorl_is_reso_166bb3_idx'), models.Index(fields=['status_code'], name='logs_errorl_status__0aac3c_idx'), models.Index(fields=['-created_at'], name='logs_errorl_created_11011b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_attempt', 'Login Attempt'), ('login_success', 'Login Success'), ('login_failure', 'Login Failure'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('account_locked', 'Account Locked'), ('suspicious_activity', 'Suspicious Activity'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach_attempt', 'Data Breach Attempt'), ('admin_action', 'Admin Action'), ('other', 'Other')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('is_investigated', models.BooleanField(default=False)),
                ('investigation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='logs_securi_event_t_b210f8_idx'), models.Index(fields=['severity', '-created_at'], name='logs_securi_severit_df70f2_idx'), models.Index(fields=['user', '-created_at'], name='logs_securi_user_id_13d43f_idx'), models.Index(fields=['ip_address'], name='logs_securi_ip_addr_92563a_idx')],
            },
        ),
    ]
