# Generated by Django 5.0.14 on 2025-08-10 00:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('is_system_tag', models.BooleanField(default=False, help_text='System-managed tag')),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Conversation Tag',
                'verbose_name_plural': 'Conversation Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('conversation_type', models.CharField(choices=[('product_inquiry', 'Product Inquiry'), ('quote_negotiation', 'Quote Negotiation'), ('bidding_round', 'Bidding Round'), ('dispute_resolution', 'Dispute Resolution'), ('general', 'General Chat')], default='product_inquiry', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='active', max_length=20)),
                ('product_request_id', models.UUIDField(blank=True, null=True)),
                ('quote_id', models.UUIDField(blank=True, null=True)),
                ('allow_new_participants', models.BooleanField(default=False)),
                ('is_bidding_enabled', models.BooleanField(default=True)),
                ('auto_archive_after_hours', models.PositiveIntegerField(default=720)),
                ('is_moderated', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('access_code', models.CharField(blank=True, max_length=50)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('moderator', 'Moderator'), ('participant', 'Participant'), ('observer', 'Observer'), ('restricted', 'Restricted')], default='participant', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned'), ('left', 'Left'), ('kicked', 'Kicked')], default='active', max_length=20)),
                ('can_send_messages', models.BooleanField(default=True)),
                ('can_share_files', models.BooleanField(default=True)),
                ('can_invite_others', models.BooleanField(default=False)),
                ('can_moderate_content', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
                ('ban_reason', models.TextField(blank=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Participant',
                'verbose_name_plural': 'Conversation Participants',
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='chat_conversations', through='chat_conversations.ConversationParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ConversationTagAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tags', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='chat_conversations.conversation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chat_conversations.conversationtag')),
            ],
            options={
                'verbose_name': 'Conversation Tag Assignment',
                'verbose_name_plural': 'Conversation Tag Assignments',
            },
        ),
        migrations.CreateModel(
            name='ConversationBookmark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, help_text='Personal note about this bookmark')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='chat_conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Bookmark',
                'verbose_name_plural': 'Conversation Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'conversation')},
            },
        ),
        migrations.CreateModel(
            name='ConversationInvite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('moderator', 'Moderator'), ('participant', 'Participant'), ('observer', 'Observer'), ('restricted', 'Restricted')], default='participant', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Personal message with invitation')),
                ('expires_at', models.DateTimeField(help_text='When this invitation expires')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat_conversations.conversation')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Invite',
                'verbose_name_plural': 'Conversation Invites',
                'indexes': [models.Index(fields=['status'], name='chat_conver_status_57e7a1_idx'), models.Index(fields=['invited_user'], name='chat_conver_invited_6e3732_idx'), models.Index(fields=['expires_at'], name='chat_conver_expires_c1b033_idx')],
                'unique_together': {('conversation', 'invited_user')},
            },
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['conversation', 'status'], name='chat_conver_convers_4c88c4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', 'status'], name='chat_conver_user_id_a76b81_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['role'], name='chat_conver_role_1e099f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['last_active_at'], name='chat_conver_last_ac_992a05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['buyer', 'status'], name='chat_conver_buyer_i_5f4851_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'status'], name='chat_conver_convers_f37fee_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['product_request_id'], name='chat_conver_product_88c5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['quote_id'], name='chat_conver_quote_i_103afe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='chat_conver_last_me_be695c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='chat_conver_created_4a7ea1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationtagassignment',
            unique_together={('conversation', 'tag')},
        ),
    ]
