# Generated by Django 5.0.14 on 2025-09-07 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOperationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('operation_type', models.CharField(choices=[('bulk_create', 'Bulk Create'), ('bulk_update', 'Bulk Update'), ('bulk_delete', 'Bulk Delete'), ('bulk_import', 'Bulk Import'), ('bulk_export', 'Bulk Export'), ('bulk_price_update', 'Bulk Price Update'), ('bulk_inventory_update', 'Bulk Inventory Update'), ('bulk_status_change', 'Bulk Status Change')], max_length=30)),
                ('operation_name', models.CharField(help_text='Human-readable name for the operation', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the operation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0, help_text='Total number of records to process')),
                ('processed_records', models.IntegerField(default=0, help_text='Number of records processed')),
                ('successful_records', models.IntegerField(default=0, help_text='Number of records successfully processed')),
                ('failed_records', models.IntegerField(default=0, help_text='Number of records that failed processing')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('results_summary', models.JSONField(blank=True, default=dict, help_text='Summary of operation results')),
                ('error_details', models.JSONField(blank=True, default=list, help_text='Details of any errors that occurred')),
                ('input_file_path', models.CharField(blank=True, help_text='Path to input file for import operations', max_length=500)),
                ('output_file_path', models.CharField(blank=True, help_text='Path to output file for export operations', max_length=500)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation_type', 'status'], name='product_log_operati_1e1103_idx'), models.Index(fields=['performed_by', 'created_at'], name='product_log_perform_498983_idx'), models.Index(fields=['status', 'created_at'], name='product_log_status_015f1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAccessLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(max_length=100)),
                ('access_type', models.CharField(choices=[('view', 'View'), ('search', 'Search'), ('filter', 'Filter'), ('export', 'Export'), ('api_access', 'API Access')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('search_query', models.CharField(blank=True, help_text='Search query if access was through search', max_length=500)),
                ('filters_applied', models.JSONField(blank=True, default=dict, help_text='Filters applied if access was through filtering')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='product_log_content_739614_idx'), models.Index(fields=['access_type', 'created_at'], name='product_log_access__0d6f82_idx'), models.Index(fields=['user', 'created_at'], name='product_log_user_id_6177ef_idx'), models.Index(fields=['ip_address', 'created_at'], name='product_log_ip_addr_ee3a06_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductChangeLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.CharField(help_text='ID of the changed object', max_length=100)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('status_change', 'Status Change'), ('price_change', 'Price Change'), ('inventory_change', 'Inventory Change'), ('image_change', 'Image Change'), ('attribute_change', 'Attribute Change'), ('bulk_update', 'Bulk Update')], help_text='Type of change made', max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Specific field that was changed', max_length=100)),
                ('old_value_encrypted', models.TextField(blank=True, help_text='Previous value (encrypted)')),
                ('new_value_encrypted', models.TextField(blank=True, help_text='New value (encrypted)')),
                ('change_reason', models.CharField(blank=True, help_text='Reason for the change', max_length=500)),
                ('change_source', models.CharField(default='manual', help_text='Source of change (manual, api, bulk_import, etc.)', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who made the change', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the client')),
                ('affects_inventory', models.BooleanField(default=False, help_text='Whether this change affects inventory levels')),
                ('affects_pricing', models.BooleanField(default=False, help_text='Whether this change affects pricing')),
                ('affects_availability', models.BooleanField(default=False, help_text='Whether this change affects product availability')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_changes', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(help_text='Type of object that was changed', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='product_log_content_7eed86_idx'), models.Index(fields=['change_type', 'created_at'], name='product_log_change__dddcec_idx'), models.Index(fields=['changed_by', 'created_at'], name='product_log_changed_24964d_idx'), models.Index(fields=['affects_inventory', 'created_at'], name='product_log_affects_a5c632_idx'), models.Index(fields=['affects_pricing', 'created_at'], name='product_log_affects_b9dea4_idx'), models.Index(fields=['field_name'], name='product_log_field_n_1173a0_idx')],
            },
        ),
    ]
