# Generated by Django 5.0.14 on 2025-08-02 01:19

import django.db.models.deletion
import otp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('is_visible', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('otp', models.CharField(help_text='One-time password for authentication.', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=otp.models.default_expires_at, help_text='Expiration time for the OTP.')),
                ('verified_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp when the OTP was verified.', null=True)),
                ('devices', models.JSONField(default=list, help_text='List of devices the OTP is valid for.')),
                ('last_updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user associated with this OTP.', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One-Time Password',
                'verbose_name_plural': 'One-Time Passwords',
                'db_table': 'authentication_otp',
                'indexes': [models.Index(fields=['otp'], name='otp_idx'), models.Index(fields=['expires_at'], name='expires_at_idx')],
            },
        ),
    ]
