# Generated by Django 5.0.14 on 2025-09-07 05:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(help_text='Name of the performance metric', max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=6, help_text='Performance metric value', max_digits=15)),
                ('metric_unit', models.CharField(help_text='Unit of measurement (ms, mb, count, etc.)', max_length=20)),
                ('operation', models.CharField(help_text='Operation being measured', max_length=200)),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint (if applicable)', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional performance metadata', null=True)),
                ('threshold_exceeded', models.BooleanField(default=False, help_text='Whether a performance threshold was exceeded')),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Severity of the performance metric', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the metric was recorded')),
            ],
            options={
                'db_table': 'performance_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_name', 'timestamp'], name='performance_metric__90f83a_idx'), models.Index(fields=['operation', 'timestamp'], name='performance_operati_e0ee5e_idx'), models.Index(fields=['threshold_exceeded', 'timestamp'], name='performance_thresho_82173d_idx'), models.Index(fields=['severity', 'timestamp'], name='performance_severit_2db4ce_idx'), models.Index(fields=['timestamp'], name='performance_timesta_63bc7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('path', models.CharField(help_text='Request path/endpoint', max_length=500)),
                ('full_url', models.TextField(help_text='Complete request URL')),
                ('query_params', models.JSONField(blank=True, help_text='Query parameters', null=True)),
                ('headers', models.JSONField(blank=True, help_text='Request headers', null=True)),
                ('request_body', models.TextField(blank=True, help_text='Request body content', null=True)),
                ('request_size', models.IntegerField(blank=True, help_text='Request size in bytes', null=True)),
                ('status_code', models.IntegerField(help_text='HTTP response status code')),
                ('response_body', models.TextField(blank=True, help_text='Response body content', null=True)),
                ('response_size', models.IntegerField(blank=True, help_text='Response size in bytes', null=True)),
                ('response_headers', models.JSONField(blank=True, help_text='Response headers', null=True)),
                ('duration_ms', models.DecimalField(blank=True, decimal_places=3, help_text='Request duration in milliseconds', max_digits=10, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session ID', max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('view_name', models.CharField(blank=True, help_text='Django view name', max_length=200, null=True)),
                ('endpoint_category', models.CharField(blank=True, help_text='API endpoint category', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed', null=True)),
                ('error_traceback', models.TextField(blank=True, help_text='Error traceback', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the request was made')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_request_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_request_timesta_df69e7_idx'), models.Index(fields=['user', 'timestamp'], name='api_request_user_id_bef004_idx'), models.Index(fields=['method', 'path'], name='api_request_method_e1cdf4_idx'), models.Index(fields=['status_code'], name='api_request_status__5b8a12_idx'), models.Index(fields=['endpoint_category'], name='api_request_endpoin_36b150_idx'), models.Index(fields=['ip_address'], name='api_request_ip_addr_9fd701_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Log severity level', max_length=10)),
                ('event_type', models.CharField(choices=[('API_REQUEST', 'API Request'), ('USER_ACTION', 'User Action'), ('SYSTEM_EVENT', 'System Event'), ('DATA_CHANGE', 'Data Change'), ('ERROR_EVENT', 'Error Event'), ('AUTHENTICATION', 'Authentication'), ('BUSINESS_LOGIC', 'Business Logic')], help_text='Type of event being logged', max_length=20)),
                ('message', models.TextField(help_text='Human-readable log message')),
                ('category', models.CharField(help_text="Log category (e.g., 'product_requests', 'analytics')", max_length=100)),
                ('subcategory', models.CharField(blank=True, help_text='Log subcategory', max_length=100, null=True)),
                ('context_data', models.JSONField(blank=True, help_text='Additional context information', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Tags for filtering and searching', null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session ID', max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code', max_length=50, null=True)),
                ('error_details', models.JSONField(blank=True, help_text='Detailed error information', null=True)),
                ('execution_time_ms', models.DecimalField(blank=True, decimal_places=3, help_text='Execution time in milliseconds', max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='application_timesta_4a65ea_idx'), models.Index(fields=['level', 'timestamp'], name='application_level_97536c_idx'), models.Index(fields=['event_type', 'timestamp'], name='application_event_t_eb924c_idx'), models.Index(fields=['category', 'timestamp'], name='application_categor_5c47b3_idx'), models.Index(fields=['user', 'timestamp'], name='application_user_id_ae0d5a_idx'), models.Index(fields=['content_type', 'object_id'], name='application_content_e115a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(help_text='ID of the category')),
                ('category_name', models.CharField(help_text='Category name at time of logging', max_length=200)),
                ('event', models.CharField(help_text='Event type (accessed, modified, searched, etc.)', max_length=50)),
                ('event_data', models.JSONField(blank=True, help_text='Additional event data', null=True)),
                ('request_count', models.IntegerField(default=1, help_text='Number of requests for this category')),
                ('search_queries', models.JSONField(blank=True, help_text='Search queries related to this category', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the event', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category_id', 'timestamp'], name='category_lo_categor_062fc4_idx'), models.Index(fields=['event', 'timestamp'], name='category_lo_event_9d7a6b_idx'), models.Index(fields=['user', 'timestamp'], name='category_lo_user_id_d107d8_idx'), models.Index(fields=['timestamp'], name='category_lo_timesta_ac93dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(help_text='Type/class of error', max_length=100)),
                ('error_message', models.TextField(help_text='Error message')),
                ('error_code', models.CharField(blank=True, help_text='Application error code', max_length=50, null=True)),
                ('stack_trace', models.TextField(blank=True, help_text='Full stack trace', null=True)),
                ('file_path', models.CharField(blank=True, help_text='File where error occurred', max_length=500, null=True)),
                ('line_number', models.IntegerField(blank=True, help_text='Line number where error occurred', null=True)),
                ('function_name', models.CharField(blank=True, help_text='Function where error occurred', max_length=200, null=True)),
                ('request_id', models.UUIDField(blank=True, help_text='Related API request ID', null=True)),
                ('method', models.CharField(blank=True, help_text='HTTP method', max_length=10, null=True)),
                ('path', models.CharField(blank=True, help_text='Request path', max_length=500, null=True)),
                ('session_id', models.CharField(blank=True, help_text='Session ID', max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('context_data', models.JSONField(blank=True, help_text='Additional error context', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the error has been resolved')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about error resolution', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the error was resolved', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the error occurred')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the error', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who encountered the error', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'error_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['error_type', 'timestamp'], name='error_log_error_t_4c1fcd_idx'), models.Index(fields=['is_resolved', 'timestamp'], name='error_log_is_reso_5cba43_idx'), models.Index(fields=['user', 'timestamp'], name='error_log_user_id_3d90d8_idx'), models.Index(fields=['request_id'], name='error_log_request_1d9e8f_idx'), models.Index(fields=['timestamp'], name='error_log_timesta_6abfea_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_request_id', models.CharField(help_text='UUID of the product request', max_length=36)),
                ('action', models.CharField(help_text='Action performed (created, updated, viewed, etc.)', max_length=50)),
                ('action_details', models.JSONField(blank=True, help_text='Additional details about the action', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('category', models.CharField(blank=True, help_text='Product request category', max_length=50, null=True)),
                ('title', models.CharField(blank=True, help_text='Product request title', max_length=200, null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Previous values (for updates)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values (for updates)', null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the action (web, mobile, api, etc.)', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_request_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product_request_id', 'timestamp'], name='product_req_product_105184_idx'), models.Index(fields=['action', 'timestamp'], name='product_req_action_5f47ed_idx'), models.Index(fields=['user', 'timestamp'], name='product_req_user_id_b443ac_idx'), models.Index(fields=['category', 'timestamp'], name='product_req_categor_d9dbc1_idx'), models.Index(fields=['timestamp'], name='product_req_timesta_b44a9c_idx')],
            },
        ),
    ]
