# Generated by Django 5.0.14 on 2025-08-02 03:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('search_radius', models.IntegerField(default=50, help_text='Search radius in kilometers', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('request_type', models.CharField(choices=[('product_inquiry', 'Product Inquiry'), ('quote_request', 'Quote Request'), ('bulk_order', 'Bulk Order'), ('custom_product', 'Custom Product'), ('unavailable_product', 'Unavailable Product Request')], max_length=30)),
                ('requester_company', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('quantity_needed', models.IntegerField(help_text='Quantity of items needed', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_of_measure', models.CharField(default='pieces', help_text='Unit of measurement (pieces, kg, meters, etc.)', max_length=50)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget per unit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget per unit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget for the entire order', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('urgency', models.CharField(choices=[('low', 'Low - No rush'), ('medium', 'Medium - Standard'), ('high', 'High - Priority'), ('urgent', 'Urgent - ASAP')], default='medium', max_length=10)),
                ('needed_by_date', models.DateTimeField(blank=True, help_text='When the product is needed by', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this request expires', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired'), ('draft', 'Draft')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('quote_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('delivery_required', models.BooleanField(default=True)),
                ('preferred_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('existing_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='products.product')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='requests/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_requests.productrequest')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('inquiry', 'Inquiry'), ('clarification', 'Clarification'), ('update', 'Update'), ('quote_submission', 'Quote Submission'), ('system', 'System Message')], default='inquiry', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal messages not visible to requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='product_requests.productrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_request_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product_requests.productrequest')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('request_type', models.CharField(choices=[('product_inquiry', 'Product Inquiry'), ('quote_request', 'Quote Request'), ('bulk_order', 'Bulk Order'), ('custom_product', 'Custom Product'), ('unavailable_product', 'Unavailable Product Request')], max_length=30)),
                ('template_data', models.JSONField(default=dict, help_text='JSON data for pre-filling request forms')),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_templates', to='categories.category')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RequestWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_on_quotes', models.BooleanField(default=True)),
                ('notify_on_updates', models.BooleanField(default=True)),
                ('notify_on_messages', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='product_requests.productrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['status', 'priority'], name='product_req_status_01de14_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['requester', 'status'], name='product_req_request_5ead2f_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['category', 'status'], name='product_req_categor_1403b6_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['expires_at'], name='product_req_expires_041cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['needed_by_date'], name='product_req_needed__2dfc39_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequest',
            index=models.Index(fields=['reference_number'], name='product_req_referen_1f05b4_idx'),
        ),
        migrations.AddIndex(
            model_name='requestmessage',
            index=models.Index(fields=['request', 'created_at'], name='product_req_request_3606ae_idx'),
        ),
        migrations.AddIndex(
            model_name='requestmessage',
            index=models.Index(fields=['sender'], name='product_req_sender__742078_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestspecification',
            unique_together={('request', 'name')},
        ),
        migrations.AddIndex(
            model_name='requesttemplate',
            index=models.Index(fields=['category', 'is_active'], name='product_req_categor_4d724f_idx'),
        ),
        migrations.AddIndex(
            model_name='requesttemplate',
            index=models.Index(fields=['request_type', 'is_active'], name='product_req_request_c78899_idx'),
        ),
        migrations.AddIndex(
            model_name='requestwatchlist',
            index=models.Index(fields=['user', 'created_at'], name='product_req_user_id_6898b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requestwatchlist',
            unique_together={('request', 'user')},
        ),
    ]
