# Generated by Django 5.0.14 on 2025-08-10 00:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFilterRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('profanity', 'Profanity Filter'), ('personal_info', 'Personal Information'), ('spam', 'Spam Detection'), ('offensive', 'Offensive Content'), ('scam', 'Scam/Fraud Detection'), ('custom', 'Custom Rule')], max_length=20)),
                ('pattern', models.TextField(help_text='Regex pattern or keyword list')),
                ('action', models.CharField(choices=[('flag', 'Flag for Review'), ('block', 'Block Message'), ('warn', 'Warn User'), ('mask', 'Mask Content'), ('replace', 'Replace with Alternative')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('language_codes', models.JSONField(default=list, help_text='Languages this rule applies to')),
                ('replacement_text', models.TextField(blank=True, help_text='Text to replace matches with')),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Content Filter Rule',
                'verbose_name_plural': 'Content Filter Rules',
                'indexes': [models.Index(fields=['rule_type'], name='chat_core_c_rule_ty_c9bbf5_idx'), models.Index(fields=['is_enabled'], name='chat_core_c_is_enab_a4f69b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LanguagePreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_language', models.CharField(default='en', max_length=10)),
                ('secondary_languages', models.JSONField(default=list)),
                ('auto_translate_enabled', models.BooleanField(default=False)),
                ('translate_from_languages', models.JSONField(default=list)),
                ('show_original_text', models.BooleanField(default=True)),
                ('date_format', models.CharField(default='%Y-%m-%d', max_length=20)),
                ('time_format', models.CharField(default='%H:%M', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Language Preference',
                'verbose_name_plural': 'Language Preferences',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('moderation', 'Content Moderation'), ('translation', 'Translation Services'), ('limits', 'System Limits'), ('features', 'Feature Flags'), ('privacy', 'Privacy Controls'), ('notifications_service', 'Notification Settings')], max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_system_managed', models.BooleanField(default=False)),
                ('is_user_configurable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'indexes': [models.Index(fields=['category'], name='chat_core_s_categor_f57e69_idx'), models.Index(fields=['key'], name='chat_core_s_key_5c7817_idx')],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_text', models.TextField()),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('translation_service', models.CharField(default='google', max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Translation Cache',
                'verbose_name_plural': 'Translation Caches',
                'indexes': [models.Index(fields=['source_language', 'target_language'], name='chat_core_t_source__4005a5_idx'), models.Index(fields=['last_used'], name='chat_core_t_last_us_38c242_idx')],
                'unique_together': {('source_text', 'source_language', 'target_language')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('message_sent', 'Message Sent'), ('message_deleted', 'Message Deleted'), ('message_edited', 'Message Edited'), ('conversation_created', 'Conversation Created'), ('conversation_deleted', 'Conversation Deleted'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('content_moderated', 'Content Moderated'), ('file_uploaded', 'File Uploaded'), ('file_deleted', 'File Deleted'), ('translation_requested', 'Translation Requested'), ('privacy_violation', 'Privacy Violation Detected'), ('spam_detected', 'Spam Content Detected'), ('profanity_detected', 'Profanity Detected'), ('personal_info_shared', 'Personal Information Shared'), ('system_config_changed', 'System Configuration Changed')], max_length=50)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'indexes': [models.Index(fields=['user'], name='chat_core_a_user_id_d35f3c_idx'), models.Index(fields=['action_type'], name='chat_core_a_action__ddb5cd_idx'), models.Index(fields=['resource_type'], name='chat_core_a_resourc_ea391d_idx'), models.Index(fields=['severity'], name='chat_core_a_severit_10586e_idx'), models.Index(fields=['created_at'], name='chat_core_a_created_fe41f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationQueue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('message', 'Chat Message'), ('file', 'File Upload'), ('profile', 'User Profile'), ('conversation', 'Conversation')], max_length=20)),
                ('content_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('reason', models.TextField()),
                ('content_snapshot', models.JSONField(help_text='Snapshot of content at time of report')),
                ('moderator_notes', models.TextField(blank=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Queue Item',
                'verbose_name_plural': 'Moderation Queue',
                'indexes': [models.Index(fields=['status'], name='chat_core_m_status_fce5c9_idx'), models.Index(fields=['priority'], name='chat_core_m_priorit_ed6def_idx'), models.Index(fields=['assigned_to'], name='chat_core_m_assigne_9405b6_idx'), models.Index(fields=['created_at'], name='chat_core_m_created_b1c4b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='buyer', max_length=20)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('identity_verified', 'Identity Verified'), ('business_verified', 'Business Verified'), ('fully_verified', 'Fully Verified')], default='unverified', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('allow_direct_messages', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=True)),
                ('allow_read_receipts', models.BooleanField(default=True)),
                ('mask_personal_info', models.BooleanField(default=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('deleted', 'Deleted'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True)),
                ('ban_expires_at', models.DateTimeField(blank=True, null=True)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('average_response_time_minutes', models.PositiveIntegerField(default=0)),
                ('reputation_score', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['role', 'status'], name='chat_core_u_role_b7ec45_idx'), models.Index(fields=['verification_status'], name='chat_core_u_verific_526532_idx'), models.Index(fields=['is_banned'], name='chat_core_u_is_bann_8071e9_idx'), models.Index(fields=['last_seen'], name='chat_core_u_last_se_082bbc_idx')],
            },
        ),
    ]
