# Generated by Django 5.0.14 on 2025-08-10 03:26

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('total_notifications', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('failed_deliveries', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('unsubscribed_count', models.PositiveIntegerField(default=0)),
                ('avg_delivery_time_ms', models.FloatField(default=0.0)),
                ('max_delivery_time_ms', models.FloatField(default=0.0)),
                ('min_delivery_time_ms', models.FloatField(default=0.0)),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('cost_per_notification', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'channel_name'],
                'indexes': [models.Index(fields=['channel_type', 'date'], name='notificatio_channel_a8bc23_idx'), models.Index(fields=['date'], name='notificatio_date_cd4458_idx')],
                'unique_together': {('channel_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NotificationStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('email_sent', models.PositiveIntegerField(default=0)),
                ('sms_sent', models.PositiveIntegerField(default=0)),
                ('push_sent', models.PositiveIntegerField(default=0)),
                ('in_app_sent', models.PositiveIntegerField(default=0)),
                ('email_success_rate', models.FloatField(default=0.0)),
                ('sms_success_rate', models.FloatField(default=0.0)),
                ('push_success_rate', models.FloatField(default=0.0)),
                ('total_opened', models.PositiveIntegerField(default=0)),
                ('total_clicked', models.PositiveIntegerField(default=0)),
                ('total_read', models.PositiveIntegerField(default=0)),
                ('avg_processing_time_ms', models.FloatField(default=0.0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('total_bounced', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='notificatio_date_51d8fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTypeAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('failed_deliveries', models.PositiveIntegerField(default=0)),
                ('total_opened', models.PositiveIntegerField(default=0)),
                ('total_clicked', models.PositiveIntegerField(default=0)),
                ('total_dismissed', models.PositiveIntegerField(default=0)),
                ('avg_processing_time_ms', models.FloatField(default=0.0)),
                ('avg_time_to_read_minutes', models.FloatField(default=0.0)),
                ('unique_recipients', models.PositiveIntegerField(default=0)),
                ('repeat_interactions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'notification_type'],
                'indexes': [models.Index(fields=['notification_type', 'date'], name='notificatio_notific_76a271_idx')],
                'unique_together': {('notification_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SystemPerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('queue_size', models.PositiveIntegerField(default=0)),
                ('avg_queue_wait_time_ms', models.FloatField(default=0.0)),
                ('max_queue_wait_time_ms', models.FloatField(default=0.0)),
                ('notifications_processed_per_minute', models.FloatField(default=0.0)),
                ('avg_processing_time_ms', models.FloatField(default=0.0)),
                ('error_rate_percentage', models.FloatField(default=0.0)),
                ('cpu_usage_percentage', models.FloatField(default=0.0)),
                ('memory_usage_percentage', models.FloatField(default=0.0)),
                ('active_channels', models.PositiveIntegerField(default=0)),
                ('failing_channels', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='notificatio_timesta_07dacb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('time_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('current_value', models.FloatField()),
                ('previous_value', models.FloatField(default=0.0)),
                ('change_percentage', models.FloatField(default=0.0)),
                ('trend_direction', models.CharField(choices=[('up', 'Increasing'), ('down', 'Decreasing'), ('stable', 'Stable')], max_length=10)),
                ('min_value', models.FloatField(default=0.0)),
                ('max_value', models.FloatField(default=0.0)),
                ('avg_value', models.FloatField(default=0.0)),
                ('std_deviation', models.FloatField(default=0.0)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_start', 'metric_name'],
                'indexes': [models.Index(fields=['metric_name', 'time_period'], name='notificatio_metric__29685e_idx'), models.Index(fields=['period_start', 'period_end'], name='notificatio_period__d59dc7_idx')],
                'unique_together': {('metric_name', 'time_period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserEngagementMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('date', models.DateField()),
                ('notifications_received', models.PositiveIntegerField(default=0)),
                ('notifications_read', models.PositiveIntegerField(default=0)),
                ('notifications_clicked', models.PositiveIntegerField(default=0)),
                ('notifications_dismissed', models.PositiveIntegerField(default=0)),
                ('avg_time_to_read_minutes', models.FloatField(default=0.0)),
                ('total_engagement_time_minutes', models.FloatField(default=0.0)),
                ('preferences_changed', models.PositiveIntegerField(default=0)),
                ('unsubscribe_events', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'user_id'],
                'indexes': [models.Index(fields=['user_id', 'date'], name='notificatio_user_id_2d4701_idx')],
                'unique_together': {('user_id', 'date')},
            },
        ),
    ]
