# Generated by Django 5.0.14 on 2025-08-10 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('return_period_days', models.PositiveIntegerField(default=30)),
                ('restocking_fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('who_pays_shipping', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('platform', 'Platform')], default='buyer', max_length=10)),
                ('requires_original_packaging', models.BooleanField(default=True)),
                ('requires_tags_attached', models.BooleanField(default=False)),
                ('allows_used_items', models.BooleanField(default=True)),
                ('applicable_categories', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', 'Defective Product'), ('not_as_described', 'Not as Described'), ('wrong_item', 'Wrong Item Received'), ('damaged_shipping', 'Damaged During Shipping'), ('quality_issues', 'Quality Issues'), ('size_fit', 'Size/Fit Issues'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('requested_outcome', models.CharField(choices=[('full_refund', 'Full Refund'), ('partial_refund', 'Partial Refund'), ('exchange', 'Exchange'), ('store_credit', 'Store Credit')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_transit', 'In Transit to Seller'), ('received', 'Received by Seller'), ('processing', 'Processing'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('return_deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests_made', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests_received', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transactionreference')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('photo_type', models.CharField(choices=[('initial', 'Initial Condition'), ('defect', 'Defect Documentation'), ('packaging', 'Packaging'), ('shipping', 'Shipping Documentation'), ('other', 'Other')], default='initial', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='returns.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_assessment', models.CharField(choices=[('excellent', 'Excellent - Like New'), ('good', 'Good - Minor Wear'), ('fair', 'Fair - Some Wear'), ('poor', 'Poor - Significant Wear'), ('damaged', 'Damaged - Not Resellable')], max_length=20)),
                ('packaging_intact', models.BooleanField(default=True)),
                ('all_items_present', models.BooleanField(default=True)),
                ('no_additional_damage', models.BooleanField(default=True)),
                ('is_acceptable', models.BooleanField()),
                ('refund_percentage', models.PositiveSmallIntegerField(default=100)),
                ('evaluation_notes', models.TextField()),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='returns.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(blank=True, max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('shipping_label_url', models.URLField(blank=True)),
                ('return_address', models.TextField()),
                ('pickup_address', models.TextField(blank=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('paid_by', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('platform', 'Platform')], default='buyer', max_length=10)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='returns.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='returns.returnrequest')),
            ],
            options={
                'verbose_name_plural': 'Return status histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
