apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- namespace-and-serviceaccount.yaml
- namespace-rbac.yaml
- secret.yaml
- configmap.yaml
- postgres.yaml
- auth-service.yaml
- chat-service.yaml
- payment-service.yaml
- resolution-service.yaml
- product-management-service.yaml
- notifications-service.yaml
- transactions-service.yaml
- reviews-service.yaml
- nginx-proxy.yaml
- load-balancer.yaml
- ingress.yaml
- network-policy.yaml
