# Generated by Django 5.0.14 on 2025-08-26 14:41

import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='valid_until',
            field=models.DateTimeField(default=quotes.models.get_default_expiry, help_text='Quote expiration'),
        ),
    ]
