apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: bidr
spec:
  template:
    spec:
      containers:
      - name: chat-service
        envFrom:
        - secretRef:
            name: chat-db-secret
