apiVersion: v1
kind: ConfigMap
metadata:
  name: bidr-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*.azurecontainer.io,*.aks.azure.com,*.westeurope.cloudapp.azure.com"
  CORS_ALLOWED_ORIGINS: "https://uat.bidr.app,https://uat-api.bidr.app"
  ENVIRONMENT: "uat"
  LOG_LEVEL: "INFO"
  ENABLE_DEBUG_TOOLBAR: "False"
  USE_HTTPS: "True"
