apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: bidr
spec:
  template:
    spec:
      containers:
      - name: notifications-service
        envFrom:
        - secretRef:
            name: notifications-db-secret
