apiVersion: apps/v1
kind: Deployment
metadata:
  name: resolution-service
  namespace: bidr
spec:
  template:
    spec:
      containers:
      - name: resolution-service
        envFrom:
        - secretRef:
            name: resolution-db-secret
